// @generated by protobuf-ts 2.11.1 with parameter long_type_string
// @generated from protobuf file "notifications/notifications.proto" (package "notifications", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { NotificationsService } from "./notifications";
import type { SendEmailResponse } from "./notifications";
import type { SendEmailRequest } from "./notifications";
import type { ListReactionsResponse } from "./notifications";
import type { ListReactionsRequest } from "./notifications";
import type { ToggleReactionResponse } from "./notifications";
import type { ToggleReactionRequest } from "./notifications";
import type { DeleteMessageResponse } from "./notifications";
import type { DeleteMessageRequest } from "./notifications";
import type { EditMessageResponse } from "./notifications";
import type { EditMessageRequest } from "./notifications";
import type { SendMessageResponse } from "./notifications";
import type { SendMessageRequest } from "./notifications";
import type { ListMessagesResponse } from "./notifications";
import type { ListMessagesRequest } from "./notifications";
import type { MarkConversationAsReadResponse } from "./notifications";
import type { MarkConversationAsReadRequest } from "./notifications";
import type { GetConversationResponse } from "./notifications";
import type { GetConversationRequest } from "./notifications";
import type { ListConversationsResponse } from "./notifications";
import type { ListConversationsRequest } from "./notifications";
import type { StartConversationResponse } from "./notifications";
import type { StartConversationRequest } from "./notifications";
import type { GetChannelPerformanceResponse } from "./notifications";
import type { GetChannelPerformanceRequest } from "./notifications";
import type { GetDeliveryStatsResponse } from "./notifications";
import type { GetDeliveryStatsRequest } from "./notifications";
import type { ToggleFeatureFlagResponse } from "./notifications";
import type { ToggleFeatureFlagRequest } from "./notifications";
import type { GetBlastStatusResponse } from "./notifications";
import type { GetBlastStatusRequest } from "./notifications";
import type { DeletePushTokenResponse } from "./notifications";
import type { DeletePushTokenRequest } from "./notifications";
import type { GetPushTokensResponse } from "./notifications";
import type { GetPushTokensRequest } from "./notifications";
import type { RegisterPushTokenResponse } from "./notifications";
import type { RegisterPushTokenRequest } from "./notifications";
import type { UpdateUserPreferencesResponse } from "./notifications";
import type { UpdateUserPreferencesRequest } from "./notifications";
import type { GetUserPreferencesResponse } from "./notifications";
import type { GetUserPreferencesRequest } from "./notifications";
import type { BlastActionResponse } from "./notifications";
import type { BlastActionRequest } from "./notifications";
import type { ListBlastsResponse } from "./notifications";
import type { ListBlastsRequest } from "./notifications";
import type { GetBlastResponse } from "./notifications";
import type { GetBlastRequest } from "./notifications";
import type { CreateBlastResponse } from "./notifications";
import type { CreateBlastRequest } from "./notifications";
import type { ListDeliveriesResponse } from "./notifications";
import type { ListDeliveriesRequest } from "./notifications";
import type { GetDeliveryResponse } from "./notifications";
import type { GetDeliveryRequest } from "./notifications";
import type { MarkAllNotificationsAsClickedResponse } from "./notifications";
import type { MarkAllNotificationsAsClickedRequest } from "./notifications";
import type { MarkNotificationAsClickedResponse } from "./notifications";
import type { MarkNotificationAsClickedRequest } from "./notifications";
import type { ListNotificationsByUserResponse } from "./notifications";
import type { ListNotificationsByUserRequest } from "./notifications";
import type { GetNotificationResponse } from "./notifications";
import type { GetNotificationRequest } from "./notifications";
import type { SendNotificationResponse } from "./notifications";
import type { SendNotificationRequest } from "./notifications";
import type { PreviewTemplateResponse } from "./notifications";
import type { PreviewTemplateRequest } from "./notifications";
import type { DeleteTemplateResponse } from "./notifications";
import type { DeleteTemplateRequest } from "./notifications";
import type { UpdateTemplateResponse } from "./notifications";
import type { UpdateTemplateRequest } from "./notifications";
import type { GetTemplateResponse } from "./notifications";
import type { GetTemplateRequest } from "./notifications";
import type { CreateTemplateResponse } from "./notifications";
import type { CreateTemplateRequest } from "./notifications";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { ListTemplatesResponse } from "./notifications";
import type { ListTemplatesRequest } from "./notifications";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * ═══════════════════════════════════════════════════════════════
 * Notifications gRPC Service
 * ═══════════════════════════════════════════════════════════════
 *
 * @generated from protobuf service notifications.NotificationsService
 */
export interface INotificationsServiceClient {
    /**
     * ── Templates ──
     *
     * @generated from protobuf rpc: ListTemplates
     */
    listTemplates(input: ListTemplatesRequest, options?: RpcOptions): UnaryCall<ListTemplatesRequest, ListTemplatesResponse>;
    /**
     * @generated from protobuf rpc: CreateTemplate
     */
    createTemplate(input: CreateTemplateRequest, options?: RpcOptions): UnaryCall<CreateTemplateRequest, CreateTemplateResponse>;
    /**
     * @generated from protobuf rpc: GetTemplate
     */
    getTemplate(input: GetTemplateRequest, options?: RpcOptions): UnaryCall<GetTemplateRequest, GetTemplateResponse>;
    /**
     * @generated from protobuf rpc: UpdateTemplate
     */
    updateTemplate(input: UpdateTemplateRequest, options?: RpcOptions): UnaryCall<UpdateTemplateRequest, UpdateTemplateResponse>;
    /**
     * @generated from protobuf rpc: DeleteTemplate
     */
    deleteTemplate(input: DeleteTemplateRequest, options?: RpcOptions): UnaryCall<DeleteTemplateRequest, DeleteTemplateResponse>;
    /**
     * @generated from protobuf rpc: PreviewTemplate
     */
    previewTemplate(input: PreviewTemplateRequest, options?: RpcOptions): UnaryCall<PreviewTemplateRequest, PreviewTemplateResponse>;
    /**
     * ── Notifications ──
     *
     * @generated from protobuf rpc: SendNotification
     */
    sendNotification(input: SendNotificationRequest, options?: RpcOptions): UnaryCall<SendNotificationRequest, SendNotificationResponse>;
    /**
     * @generated from protobuf rpc: GetNotification
     */
    getNotification(input: GetNotificationRequest, options?: RpcOptions): UnaryCall<GetNotificationRequest, GetNotificationResponse>;
    /**
     * @generated from protobuf rpc: ListNotificationsByUser
     */
    listNotificationsByUser(input: ListNotificationsByUserRequest, options?: RpcOptions): UnaryCall<ListNotificationsByUserRequest, ListNotificationsByUserResponse>;
    /**
     * @generated from protobuf rpc: MarkNotificationAsClicked
     */
    markNotificationAsClicked(input: MarkNotificationAsClickedRequest, options?: RpcOptions): UnaryCall<MarkNotificationAsClickedRequest, MarkNotificationAsClickedResponse>;
    /**
     * @generated from protobuf rpc: MarkAllNotificationsAsClicked
     */
    markAllNotificationsAsClicked(input: MarkAllNotificationsAsClickedRequest, options?: RpcOptions): UnaryCall<MarkAllNotificationsAsClickedRequest, MarkAllNotificationsAsClickedResponse>;
    /**
     * ── Deliveries ──
     *
     * @generated from protobuf rpc: GetDelivery
     */
    getDelivery(input: GetDeliveryRequest, options?: RpcOptions): UnaryCall<GetDeliveryRequest, GetDeliveryResponse>;
    /**
     * @generated from protobuf rpc: ListDeliveries
     */
    listDeliveries(input: ListDeliveriesRequest, options?: RpcOptions): UnaryCall<ListDeliveriesRequest, ListDeliveriesResponse>;
    /**
     * ── Blasts ──
     *
     * @generated from protobuf rpc: CreateBlast
     */
    createBlast(input: CreateBlastRequest, options?: RpcOptions): UnaryCall<CreateBlastRequest, CreateBlastResponse>;
    /**
     * @generated from protobuf rpc: GetBlast
     */
    getBlast(input: GetBlastRequest, options?: RpcOptions): UnaryCall<GetBlastRequest, GetBlastResponse>;
    /**
     * @generated from protobuf rpc: ListBlasts
     */
    listBlasts(input: ListBlastsRequest, options?: RpcOptions): UnaryCall<ListBlastsRequest, ListBlastsResponse>;
    /**
     * @generated from protobuf rpc: PauseBlast
     */
    pauseBlast(input: BlastActionRequest, options?: RpcOptions): UnaryCall<BlastActionRequest, BlastActionResponse>;
    /**
     * @generated from protobuf rpc: CancelBlast
     */
    cancelBlast(input: BlastActionRequest, options?: RpcOptions): UnaryCall<BlastActionRequest, BlastActionResponse>;
    /**
     * @generated from protobuf rpc: ResumeBlast
     */
    resumeBlast(input: BlastActionRequest, options?: RpcOptions): UnaryCall<BlastActionRequest, BlastActionResponse>;
    /**
     * ── User Preferences ──
     *
     * @generated from protobuf rpc: GetUserPreferences
     */
    getUserPreferences(input: GetUserPreferencesRequest, options?: RpcOptions): UnaryCall<GetUserPreferencesRequest, GetUserPreferencesResponse>;
    /**
     * @generated from protobuf rpc: UpdateUserPreferences
     */
    updateUserPreferences(input: UpdateUserPreferencesRequest, options?: RpcOptions): UnaryCall<UpdateUserPreferencesRequest, UpdateUserPreferencesResponse>;
    /**
     * ── Push Tokens ──
     *
     * @generated from protobuf rpc: RegisterPushToken
     */
    registerPushToken(input: RegisterPushTokenRequest, options?: RpcOptions): UnaryCall<RegisterPushTokenRequest, RegisterPushTokenResponse>;
    /**
     * @generated from protobuf rpc: GetPushTokens
     */
    getPushTokens(input: GetPushTokensRequest, options?: RpcOptions): UnaryCall<GetPushTokensRequest, GetPushTokensResponse>;
    /**
     * @generated from protobuf rpc: DeletePushToken
     */
    deletePushToken(input: DeletePushTokenRequest, options?: RpcOptions): UnaryCall<DeletePushTokenRequest, DeletePushTokenResponse>;
    /**
     * ── Admin ──
     *
     * @generated from protobuf rpc: GetBlastStatus
     */
    getBlastStatus(input: GetBlastStatusRequest, options?: RpcOptions): UnaryCall<GetBlastStatusRequest, GetBlastStatusResponse>;
    /**
     * @generated from protobuf rpc: ToggleFeatureFlag
     */
    toggleFeatureFlag(input: ToggleFeatureFlagRequest, options?: RpcOptions): UnaryCall<ToggleFeatureFlagRequest, ToggleFeatureFlagResponse>;
    /**
     * ── Analytics ──
     *
     * @generated from protobuf rpc: GetDeliveryStats
     */
    getDeliveryStats(input: GetDeliveryStatsRequest, options?: RpcOptions): UnaryCall<GetDeliveryStatsRequest, GetDeliveryStatsResponse>;
    /**
     * @generated from protobuf rpc: GetChannelPerformance
     */
    getChannelPerformance(input: GetChannelPerformanceRequest, options?: RpcOptions): UnaryCall<GetChannelPerformanceRequest, GetChannelPerformanceResponse>;
    /**
     * ── Inbox: Conversations ──
     *
     * @generated from protobuf rpc: StartConversation
     */
    startConversation(input: StartConversationRequest, options?: RpcOptions): UnaryCall<StartConversationRequest, StartConversationResponse>;
    /**
     * @generated from protobuf rpc: ListConversations
     */
    listConversations(input: ListConversationsRequest, options?: RpcOptions): UnaryCall<ListConversationsRequest, ListConversationsResponse>;
    /**
     * @generated from protobuf rpc: GetConversation
     */
    getConversation(input: GetConversationRequest, options?: RpcOptions): UnaryCall<GetConversationRequest, GetConversationResponse>;
    /**
     * @generated from protobuf rpc: MarkConversationAsRead
     */
    markConversationAsRead(input: MarkConversationAsReadRequest, options?: RpcOptions): UnaryCall<MarkConversationAsReadRequest, MarkConversationAsReadResponse>;
    /**
     * ── Inbox: Messages ──
     *
     * @generated from protobuf rpc: ListMessages
     */
    listMessages(input: ListMessagesRequest, options?: RpcOptions): UnaryCall<ListMessagesRequest, ListMessagesResponse>;
    /**
     * @generated from protobuf rpc: SendMessage
     */
    sendMessage(input: SendMessageRequest, options?: RpcOptions): UnaryCall<SendMessageRequest, SendMessageResponse>;
    /**
     * @generated from protobuf rpc: EditMessage
     */
    editMessage(input: EditMessageRequest, options?: RpcOptions): UnaryCall<EditMessageRequest, EditMessageResponse>;
    /**
     * @generated from protobuf rpc: DeleteMessage
     */
    deleteMessage(input: DeleteMessageRequest, options?: RpcOptions): UnaryCall<DeleteMessageRequest, DeleteMessageResponse>;
    /**
     * ── Inbox: Reactions ──
     *
     * @generated from protobuf rpc: ToggleReaction
     */
    toggleReaction(input: ToggleReactionRequest, options?: RpcOptions): UnaryCall<ToggleReactionRequest, ToggleReactionResponse>;
    /**
     * @generated from protobuf rpc: ListReactions
     */
    listReactions(input: ListReactionsRequest, options?: RpcOptions): UnaryCall<ListReactionsRequest, ListReactionsResponse>;
    /**
     * ── Email ──
     *
     * @generated from protobuf rpc: SendEmail
     */
    sendEmail(input: SendEmailRequest, options?: RpcOptions): UnaryCall<SendEmailRequest, SendEmailResponse>;
}
/**
 * ═══════════════════════════════════════════════════════════════
 * Notifications gRPC Service
 * ═══════════════════════════════════════════════════════════════
 *
 * @generated from protobuf service notifications.NotificationsService
 */
export class NotificationsServiceClient implements INotificationsServiceClient, ServiceInfo {
    typeName = NotificationsService.typeName;
    methods = NotificationsService.methods;
    options = NotificationsService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * ── Templates ──
     *
     * @generated from protobuf rpc: ListTemplates
     */
    listTemplates(input: ListTemplatesRequest, options?: RpcOptions): UnaryCall<ListTemplatesRequest, ListTemplatesResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListTemplatesRequest, ListTemplatesResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CreateTemplate
     */
    createTemplate(input: CreateTemplateRequest, options?: RpcOptions): UnaryCall<CreateTemplateRequest, CreateTemplateResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreateTemplateRequest, CreateTemplateResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetTemplate
     */
    getTemplate(input: GetTemplateRequest, options?: RpcOptions): UnaryCall<GetTemplateRequest, GetTemplateResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetTemplateRequest, GetTemplateResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateTemplate
     */
    updateTemplate(input: UpdateTemplateRequest, options?: RpcOptions): UnaryCall<UpdateTemplateRequest, UpdateTemplateResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateTemplateRequest, UpdateTemplateResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteTemplate
     */
    deleteTemplate(input: DeleteTemplateRequest, options?: RpcOptions): UnaryCall<DeleteTemplateRequest, DeleteTemplateResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteTemplateRequest, DeleteTemplateResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: PreviewTemplate
     */
    previewTemplate(input: PreviewTemplateRequest, options?: RpcOptions): UnaryCall<PreviewTemplateRequest, PreviewTemplateResponse> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<PreviewTemplateRequest, PreviewTemplateResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * ── Notifications ──
     *
     * @generated from protobuf rpc: SendNotification
     */
    sendNotification(input: SendNotificationRequest, options?: RpcOptions): UnaryCall<SendNotificationRequest, SendNotificationResponse> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<SendNotificationRequest, SendNotificationResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetNotification
     */
    getNotification(input: GetNotificationRequest, options?: RpcOptions): UnaryCall<GetNotificationRequest, GetNotificationResponse> {
        const method = this.methods[7], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetNotificationRequest, GetNotificationResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListNotificationsByUser
     */
    listNotificationsByUser(input: ListNotificationsByUserRequest, options?: RpcOptions): UnaryCall<ListNotificationsByUserRequest, ListNotificationsByUserResponse> {
        const method = this.methods[8], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListNotificationsByUserRequest, ListNotificationsByUserResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: MarkNotificationAsClicked
     */
    markNotificationAsClicked(input: MarkNotificationAsClickedRequest, options?: RpcOptions): UnaryCall<MarkNotificationAsClickedRequest, MarkNotificationAsClickedResponse> {
        const method = this.methods[9], opt = this._transport.mergeOptions(options);
        return stackIntercept<MarkNotificationAsClickedRequest, MarkNotificationAsClickedResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: MarkAllNotificationsAsClicked
     */
    markAllNotificationsAsClicked(input: MarkAllNotificationsAsClickedRequest, options?: RpcOptions): UnaryCall<MarkAllNotificationsAsClickedRequest, MarkAllNotificationsAsClickedResponse> {
        const method = this.methods[10], opt = this._transport.mergeOptions(options);
        return stackIntercept<MarkAllNotificationsAsClickedRequest, MarkAllNotificationsAsClickedResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * ── Deliveries ──
     *
     * @generated from protobuf rpc: GetDelivery
     */
    getDelivery(input: GetDeliveryRequest, options?: RpcOptions): UnaryCall<GetDeliveryRequest, GetDeliveryResponse> {
        const method = this.methods[11], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetDeliveryRequest, GetDeliveryResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListDeliveries
     */
    listDeliveries(input: ListDeliveriesRequest, options?: RpcOptions): UnaryCall<ListDeliveriesRequest, ListDeliveriesResponse> {
        const method = this.methods[12], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListDeliveriesRequest, ListDeliveriesResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * ── Blasts ──
     *
     * @generated from protobuf rpc: CreateBlast
     */
    createBlast(input: CreateBlastRequest, options?: RpcOptions): UnaryCall<CreateBlastRequest, CreateBlastResponse> {
        const method = this.methods[13], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreateBlastRequest, CreateBlastResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetBlast
     */
    getBlast(input: GetBlastRequest, options?: RpcOptions): UnaryCall<GetBlastRequest, GetBlastResponse> {
        const method = this.methods[14], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetBlastRequest, GetBlastResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListBlasts
     */
    listBlasts(input: ListBlastsRequest, options?: RpcOptions): UnaryCall<ListBlastsRequest, ListBlastsResponse> {
        const method = this.methods[15], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListBlastsRequest, ListBlastsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: PauseBlast
     */
    pauseBlast(input: BlastActionRequest, options?: RpcOptions): UnaryCall<BlastActionRequest, BlastActionResponse> {
        const method = this.methods[16], opt = this._transport.mergeOptions(options);
        return stackIntercept<BlastActionRequest, BlastActionResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CancelBlast
     */
    cancelBlast(input: BlastActionRequest, options?: RpcOptions): UnaryCall<BlastActionRequest, BlastActionResponse> {
        const method = this.methods[17], opt = this._transport.mergeOptions(options);
        return stackIntercept<BlastActionRequest, BlastActionResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ResumeBlast
     */
    resumeBlast(input: BlastActionRequest, options?: RpcOptions): UnaryCall<BlastActionRequest, BlastActionResponse> {
        const method = this.methods[18], opt = this._transport.mergeOptions(options);
        return stackIntercept<BlastActionRequest, BlastActionResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * ── User Preferences ──
     *
     * @generated from protobuf rpc: GetUserPreferences
     */
    getUserPreferences(input: GetUserPreferencesRequest, options?: RpcOptions): UnaryCall<GetUserPreferencesRequest, GetUserPreferencesResponse> {
        const method = this.methods[19], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetUserPreferencesRequest, GetUserPreferencesResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateUserPreferences
     */
    updateUserPreferences(input: UpdateUserPreferencesRequest, options?: RpcOptions): UnaryCall<UpdateUserPreferencesRequest, UpdateUserPreferencesResponse> {
        const method = this.methods[20], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateUserPreferencesRequest, UpdateUserPreferencesResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * ── Push Tokens ──
     *
     * @generated from protobuf rpc: RegisterPushToken
     */
    registerPushToken(input: RegisterPushTokenRequest, options?: RpcOptions): UnaryCall<RegisterPushTokenRequest, RegisterPushTokenResponse> {
        const method = this.methods[21], opt = this._transport.mergeOptions(options);
        return stackIntercept<RegisterPushTokenRequest, RegisterPushTokenResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetPushTokens
     */
    getPushTokens(input: GetPushTokensRequest, options?: RpcOptions): UnaryCall<GetPushTokensRequest, GetPushTokensResponse> {
        const method = this.methods[22], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetPushTokensRequest, GetPushTokensResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeletePushToken
     */
    deletePushToken(input: DeletePushTokenRequest, options?: RpcOptions): UnaryCall<DeletePushTokenRequest, DeletePushTokenResponse> {
        const method = this.methods[23], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeletePushTokenRequest, DeletePushTokenResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * ── Admin ──
     *
     * @generated from protobuf rpc: GetBlastStatus
     */
    getBlastStatus(input: GetBlastStatusRequest, options?: RpcOptions): UnaryCall<GetBlastStatusRequest, GetBlastStatusResponse> {
        const method = this.methods[24], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetBlastStatusRequest, GetBlastStatusResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ToggleFeatureFlag
     */
    toggleFeatureFlag(input: ToggleFeatureFlagRequest, options?: RpcOptions): UnaryCall<ToggleFeatureFlagRequest, ToggleFeatureFlagResponse> {
        const method = this.methods[25], opt = this._transport.mergeOptions(options);
        return stackIntercept<ToggleFeatureFlagRequest, ToggleFeatureFlagResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * ── Analytics ──
     *
     * @generated from protobuf rpc: GetDeliveryStats
     */
    getDeliveryStats(input: GetDeliveryStatsRequest, options?: RpcOptions): UnaryCall<GetDeliveryStatsRequest, GetDeliveryStatsResponse> {
        const method = this.methods[26], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetDeliveryStatsRequest, GetDeliveryStatsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetChannelPerformance
     */
    getChannelPerformance(input: GetChannelPerformanceRequest, options?: RpcOptions): UnaryCall<GetChannelPerformanceRequest, GetChannelPerformanceResponse> {
        const method = this.methods[27], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetChannelPerformanceRequest, GetChannelPerformanceResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * ── Inbox: Conversations ──
     *
     * @generated from protobuf rpc: StartConversation
     */
    startConversation(input: StartConversationRequest, options?: RpcOptions): UnaryCall<StartConversationRequest, StartConversationResponse> {
        const method = this.methods[28], opt = this._transport.mergeOptions(options);
        return stackIntercept<StartConversationRequest, StartConversationResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListConversations
     */
    listConversations(input: ListConversationsRequest, options?: RpcOptions): UnaryCall<ListConversationsRequest, ListConversationsResponse> {
        const method = this.methods[29], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListConversationsRequest, ListConversationsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetConversation
     */
    getConversation(input: GetConversationRequest, options?: RpcOptions): UnaryCall<GetConversationRequest, GetConversationResponse> {
        const method = this.methods[30], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetConversationRequest, GetConversationResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: MarkConversationAsRead
     */
    markConversationAsRead(input: MarkConversationAsReadRequest, options?: RpcOptions): UnaryCall<MarkConversationAsReadRequest, MarkConversationAsReadResponse> {
        const method = this.methods[31], opt = this._transport.mergeOptions(options);
        return stackIntercept<MarkConversationAsReadRequest, MarkConversationAsReadResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * ── Inbox: Messages ──
     *
     * @generated from protobuf rpc: ListMessages
     */
    listMessages(input: ListMessagesRequest, options?: RpcOptions): UnaryCall<ListMessagesRequest, ListMessagesResponse> {
        const method = this.methods[32], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListMessagesRequest, ListMessagesResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SendMessage
     */
    sendMessage(input: SendMessageRequest, options?: RpcOptions): UnaryCall<SendMessageRequest, SendMessageResponse> {
        const method = this.methods[33], opt = this._transport.mergeOptions(options);
        return stackIntercept<SendMessageRequest, SendMessageResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: EditMessage
     */
    editMessage(input: EditMessageRequest, options?: RpcOptions): UnaryCall<EditMessageRequest, EditMessageResponse> {
        const method = this.methods[34], opt = this._transport.mergeOptions(options);
        return stackIntercept<EditMessageRequest, EditMessageResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteMessage
     */
    deleteMessage(input: DeleteMessageRequest, options?: RpcOptions): UnaryCall<DeleteMessageRequest, DeleteMessageResponse> {
        const method = this.methods[35], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteMessageRequest, DeleteMessageResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * ── Inbox: Reactions ──
     *
     * @generated from protobuf rpc: ToggleReaction
     */
    toggleReaction(input: ToggleReactionRequest, options?: RpcOptions): UnaryCall<ToggleReactionRequest, ToggleReactionResponse> {
        const method = this.methods[36], opt = this._transport.mergeOptions(options);
        return stackIntercept<ToggleReactionRequest, ToggleReactionResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListReactions
     */
    listReactions(input: ListReactionsRequest, options?: RpcOptions): UnaryCall<ListReactionsRequest, ListReactionsResponse> {
        const method = this.methods[37], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListReactionsRequest, ListReactionsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * ── Email ──
     *
     * @generated from protobuf rpc: SendEmail
     */
    sendEmail(input: SendEmailRequest, options?: RpcOptions): UnaryCall<SendEmailRequest, SendEmailResponse> {
        const method = this.methods[38], opt = this._transport.mergeOptions(options);
        return stackIntercept<SendEmailRequest, SendEmailResponse>("unary", this._transport, method, opt, input);
    }
}
