// @generated by protobuf-ts 2.11.1 with parameter long_type_string
// @generated from protobuf file "payments/payments.proto" (package "payments", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { PaymentsService } from "./payments";
import type { UpdatePaymentMethodNicknameResponse } from "./payments";
import type { UpdatePaymentMethodNicknameRequest } from "./payments";
import type { RemovePaymentMethodResponse } from "./payments";
import type { RemovePaymentMethodRequest } from "./payments";
import type { SetDefaultPaymentMethodResponse } from "./payments";
import type { SetDefaultPaymentMethodRequest } from "./payments";
import type { GetDefaultPaymentMethodResponse } from "./payments";
import type { GetDefaultPaymentMethodRequest } from "./payments";
import type { GetPaymentMethodsResponse } from "./payments";
import type { GetPaymentMethodsRequest } from "./payments";
import type { AddPaymentMethodResponse } from "./payments";
import type { AddPaymentMethodRequest } from "./payments";
import type { GetUserAnalyticsResponse } from "./payments";
import type { GetUserAnalyticsRequest } from "./payments";
import type { ForecastRevenueResponse } from "./payments";
import type { ForecastRevenueRequest } from "./payments";
import type { GetCohortAnalysisResponse } from "./payments";
import type { GetCohortAnalysisRequest } from "./payments";
import type { GetRevenueMetricsResponse } from "./payments";
import type { GetRevenueMetricsRequest } from "./payments";
import type { GetChurnMetricsResponse } from "./payments";
import type { GetChurnMetricsRequest } from "./payments";
import type { GetMRRMetricsResponse } from "./payments";
import type { GetMRRMetricsRequest } from "./payments";
import type { GetAnalyticsResponse } from "./payments";
import type { GetAnalyticsRequest } from "./payments";
import type { UpdateFraudRuleResponse } from "./payments";
import type { UpdateFraudRuleRequest } from "./payments";
import type { GetFraudRulesResponse } from "./payments";
import type { GetFraudRulesRequest } from "./payments";
import type { RemoveIPFromBlacklistResponse } from "./payments";
import type { RemoveIPFromBlacklistRequest } from "./payments";
import type { RemovePhoneFromBlacklistResponse } from "./payments";
import type { RemovePhoneFromBlacklistRequest } from "./payments";
import type { BlacklistIPResponse } from "./payments";
import type { BlacklistIPRequest } from "./payments";
import type { BlacklistPhoneResponse } from "./payments";
import type { BlacklistPhoneRequest } from "./payments";
import type { GetBlacklistedIPsResponse } from "./payments";
import type { GetBlacklistedIPsRequest } from "./payments";
import type { GetBlacklistedPhonesResponse } from "./payments";
import type { GetBlacklistedPhonesRequest } from "./payments";
import type { GetFlaggedUsersResponse } from "./payments";
import type { GetFlaggedUsersRequest } from "./payments";
import type { GetFraudStatsResponse } from "./payments";
import type { GetFraudStatsRequest } from "./payments";
import type { GetCreditBalanceResponse } from "./payments";
import type { GetCreditBalanceRequest } from "./payments";
import type { GetProrationHistoryResponse } from "./payments";
import type { GetProrationHistoryRequest } from "./payments";
import type { ChangePlanResponse } from "./payments";
import type { ChangePlanRequest } from "./payments";
import type { PreviewProrationResponse } from "./payments";
import type { PreviewProrationRequest } from "./payments";
import type { EmailReceiptResponse } from "./payments";
import type { EmailReceiptRequest } from "./payments";
import type { DownloadReceiptResponse } from "./payments";
import type { DownloadReceiptRequest } from "./payments";
import type { CheckPaymentStatusResponse } from "./payments";
import type { CheckPaymentStatusRequest } from "./payments";
import type { ListMyPaymentsResponse } from "./payments";
import type { ListMyPaymentsRequest } from "./payments";
import type { GetPaymentResponse } from "./payments";
import type { GetPaymentRequest } from "./payments";
import type { InitiatePaymentResponse } from "./payments";
import type { InitiatePaymentRequest } from "./payments";
import type { CreateSubscriptionCheckoutResponse } from "./payments";
import type { CreateSubscriptionCheckoutRequest } from "./payments";
import type { GetCancellationStatusResponse } from "./payments";
import type { GetCancellationStatusRequest } from "./payments";
import type { UndoCancellationResponse } from "./payments";
import type { UndoCancellationRequest } from "./payments";
import type { ConfirmCancellationResponse } from "./payments";
import type { ConfirmCancellationRequest } from "./payments";
import type { AcceptRetentionOfferResponse } from "./payments";
import type { AcceptRetentionOfferRequest } from "./payments";
import type { InitiateCancellationResponse } from "./payments";
import type { InitiateCancellationRequest } from "./payments";
import type { GetPauseStatusResponse } from "./payments";
import type { GetPauseStatusRequest } from "./payments";
import type { ResumeSubscriptionResponse } from "./payments";
import type { ResumeSubscriptionRequest } from "./payments";
import type { PauseSubscriptionResponse } from "./payments";
import type { PauseSubscriptionRequest } from "./payments";
import type { CheckSubscriptionAccessResponse } from "./payments";
import type { CheckSubscriptionAccessRequest } from "./payments";
import type { CancelSubscriptionResponse } from "./payments";
import type { CancelSubscriptionRequest } from "./payments";
import type { ListMySubscriptionsResponse } from "./payments";
import type { ListMySubscriptionsRequest } from "./payments";
import type { GetMySubscriptionResponse } from "./payments";
import type { GetMySubscriptionRequest } from "./payments";
import type { GetSubscriptionResponse } from "./payments";
import type { GetSubscriptionRequest } from "./payments";
import type { CreateSubscriptionResponse } from "./payments";
import type { CreateSubscriptionRequest } from "./payments";
import type { GetPlanResponse } from "./payments";
import type { GetPlanRequest } from "./payments";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { GetPlansResponse } from "./payments";
import type { GetPlansRequest } from "./payments";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * Payments Service Definition
 *
 * @generated from protobuf service payments.PaymentsService
 */
export interface IPaymentsServiceClient {
    /**
     * Plan management
     *
     * @generated from protobuf rpc: GetPlans
     */
    getPlans(input: GetPlansRequest, options?: RpcOptions): UnaryCall<GetPlansRequest, GetPlansResponse>;
    /**
     * @generated from protobuf rpc: GetPlan
     */
    getPlan(input: GetPlanRequest, options?: RpcOptions): UnaryCall<GetPlanRequest, GetPlanResponse>;
    /**
     * Subscription management
     *
     * @generated from protobuf rpc: CreateSubscription
     */
    createSubscription(input: CreateSubscriptionRequest, options?: RpcOptions): UnaryCall<CreateSubscriptionRequest, CreateSubscriptionResponse>;
    /**
     * @generated from protobuf rpc: GetSubscription
     */
    getSubscription(input: GetSubscriptionRequest, options?: RpcOptions): UnaryCall<GetSubscriptionRequest, GetSubscriptionResponse>;
    /**
     * @generated from protobuf rpc: GetMySubscription
     */
    getMySubscription(input: GetMySubscriptionRequest, options?: RpcOptions): UnaryCall<GetMySubscriptionRequest, GetMySubscriptionResponse>;
    /**
     * @generated from protobuf rpc: ListMySubscriptions
     */
    listMySubscriptions(input: ListMySubscriptionsRequest, options?: RpcOptions): UnaryCall<ListMySubscriptionsRequest, ListMySubscriptionsResponse>;
    /**
     * @generated from protobuf rpc: CancelSubscription
     */
    cancelSubscription(input: CancelSubscriptionRequest, options?: RpcOptions): UnaryCall<CancelSubscriptionRequest, CancelSubscriptionResponse>;
    /**
     * @generated from protobuf rpc: CheckSubscriptionAccess
     */
    checkSubscriptionAccess(input: CheckSubscriptionAccessRequest, options?: RpcOptions): UnaryCall<CheckSubscriptionAccessRequest, CheckSubscriptionAccessResponse>;
    /**
     * Pause/Resume subscription
     *
     * @generated from protobuf rpc: PauseSubscription
     */
    pauseSubscription(input: PauseSubscriptionRequest, options?: RpcOptions): UnaryCall<PauseSubscriptionRequest, PauseSubscriptionResponse>;
    /**
     * @generated from protobuf rpc: ResumeSubscription
     */
    resumeSubscription(input: ResumeSubscriptionRequest, options?: RpcOptions): UnaryCall<ResumeSubscriptionRequest, ResumeSubscriptionResponse>;
    /**
     * @generated from protobuf rpc: GetPauseStatus
     */
    getPauseStatus(input: GetPauseStatusRequest, options?: RpcOptions): UnaryCall<GetPauseStatusRequest, GetPauseStatusResponse>;
    /**
     * Self-service cancellation
     *
     * @generated from protobuf rpc: InitiateCancellation
     */
    initiateCancellation(input: InitiateCancellationRequest, options?: RpcOptions): UnaryCall<InitiateCancellationRequest, InitiateCancellationResponse>;
    /**
     * @generated from protobuf rpc: AcceptRetentionOffer
     */
    acceptRetentionOffer(input: AcceptRetentionOfferRequest, options?: RpcOptions): UnaryCall<AcceptRetentionOfferRequest, AcceptRetentionOfferResponse>;
    /**
     * @generated from protobuf rpc: ConfirmCancellation
     */
    confirmCancellation(input: ConfirmCancellationRequest, options?: RpcOptions): UnaryCall<ConfirmCancellationRequest, ConfirmCancellationResponse>;
    /**
     * @generated from protobuf rpc: UndoCancellation
     */
    undoCancellation(input: UndoCancellationRequest, options?: RpcOptions): UnaryCall<UndoCancellationRequest, UndoCancellationResponse>;
    /**
     * @generated from protobuf rpc: GetCancellationStatus
     */
    getCancellationStatus(input: GetCancellationStatusRequest, options?: RpcOptions): UnaryCall<GetCancellationStatusRequest, GetCancellationStatusResponse>;
    /**
     * Payment processing
     *
     * @generated from protobuf rpc: CreateSubscriptionCheckout
     */
    createSubscriptionCheckout(input: CreateSubscriptionCheckoutRequest, options?: RpcOptions): UnaryCall<CreateSubscriptionCheckoutRequest, CreateSubscriptionCheckoutResponse>;
    /**
     * @generated from protobuf rpc: InitiatePayment
     */
    initiatePayment(input: InitiatePaymentRequest, options?: RpcOptions): UnaryCall<InitiatePaymentRequest, InitiatePaymentResponse>;
    /**
     * @generated from protobuf rpc: GetPayment
     */
    getPayment(input: GetPaymentRequest, options?: RpcOptions): UnaryCall<GetPaymentRequest, GetPaymentResponse>;
    /**
     * @generated from protobuf rpc: ListMyPayments
     */
    listMyPayments(input: ListMyPaymentsRequest, options?: RpcOptions): UnaryCall<ListMyPaymentsRequest, ListMyPaymentsResponse>;
    /**
     * @generated from protobuf rpc: CheckPaymentStatus
     */
    checkPaymentStatus(input: CheckPaymentStatusRequest, options?: RpcOptions): UnaryCall<CheckPaymentStatusRequest, CheckPaymentStatusResponse>;
    /**
     * @generated from protobuf rpc: DownloadReceipt
     */
    downloadReceipt(input: DownloadReceiptRequest, options?: RpcOptions): UnaryCall<DownloadReceiptRequest, DownloadReceiptResponse>;
    /**
     * @generated from protobuf rpc: EmailReceipt
     */
    emailReceipt(input: EmailReceiptRequest, options?: RpcOptions): UnaryCall<EmailReceiptRequest, EmailReceiptResponse>;
    /**
     * Proration management
     *
     * @generated from protobuf rpc: PreviewProration
     */
    previewProration(input: PreviewProrationRequest, options?: RpcOptions): UnaryCall<PreviewProrationRequest, PreviewProrationResponse>;
    /**
     * @generated from protobuf rpc: ChangePlan
     */
    changePlan(input: ChangePlanRequest, options?: RpcOptions): UnaryCall<ChangePlanRequest, ChangePlanResponse>;
    /**
     * @generated from protobuf rpc: GetProrationHistory
     */
    getProrationHistory(input: GetProrationHistoryRequest, options?: RpcOptions): UnaryCall<GetProrationHistoryRequest, GetProrationHistoryResponse>;
    /**
     * @generated from protobuf rpc: GetCreditBalance
     */
    getCreditBalance(input: GetCreditBalanceRequest, options?: RpcOptions): UnaryCall<GetCreditBalanceRequest, GetCreditBalanceResponse>;
    /**
     * Fraud prevention admin
     *
     * @generated from protobuf rpc: GetFraudStats
     */
    getFraudStats(input: GetFraudStatsRequest, options?: RpcOptions): UnaryCall<GetFraudStatsRequest, GetFraudStatsResponse>;
    /**
     * @generated from protobuf rpc: GetFlaggedUsers
     */
    getFlaggedUsers(input: GetFlaggedUsersRequest, options?: RpcOptions): UnaryCall<GetFlaggedUsersRequest, GetFlaggedUsersResponse>;
    /**
     * @generated from protobuf rpc: GetBlacklistedPhones
     */
    getBlacklistedPhones(input: GetBlacklistedPhonesRequest, options?: RpcOptions): UnaryCall<GetBlacklistedPhonesRequest, GetBlacklistedPhonesResponse>;
    /**
     * @generated from protobuf rpc: GetBlacklistedIPs
     */
    getBlacklistedIPs(input: GetBlacklistedIPsRequest, options?: RpcOptions): UnaryCall<GetBlacklistedIPsRequest, GetBlacklistedIPsResponse>;
    /**
     * @generated from protobuf rpc: BlacklistPhone
     */
    blacklistPhone(input: BlacklistPhoneRequest, options?: RpcOptions): UnaryCall<BlacklistPhoneRequest, BlacklistPhoneResponse>;
    /**
     * @generated from protobuf rpc: BlacklistIP
     */
    blacklistIP(input: BlacklistIPRequest, options?: RpcOptions): UnaryCall<BlacklistIPRequest, BlacklistIPResponse>;
    /**
     * @generated from protobuf rpc: RemovePhoneFromBlacklist
     */
    removePhoneFromBlacklist(input: RemovePhoneFromBlacklistRequest, options?: RpcOptions): UnaryCall<RemovePhoneFromBlacklistRequest, RemovePhoneFromBlacklistResponse>;
    /**
     * @generated from protobuf rpc: RemoveIPFromBlacklist
     */
    removeIPFromBlacklist(input: RemoveIPFromBlacklistRequest, options?: RpcOptions): UnaryCall<RemoveIPFromBlacklistRequest, RemoveIPFromBlacklistResponse>;
    /**
     * @generated from protobuf rpc: GetFraudRules
     */
    getFraudRules(input: GetFraudRulesRequest, options?: RpcOptions): UnaryCall<GetFraudRulesRequest, GetFraudRulesResponse>;
    /**
     * @generated from protobuf rpc: UpdateFraudRule
     */
    updateFraudRule(input: UpdateFraudRuleRequest, options?: RpcOptions): UnaryCall<UpdateFraudRuleRequest, UpdateFraudRuleResponse>;
    /**
     * Analytics endpoints
     *
     * @generated from protobuf rpc: GetAnalytics
     */
    getAnalytics(input: GetAnalyticsRequest, options?: RpcOptions): UnaryCall<GetAnalyticsRequest, GetAnalyticsResponse>;
    /**
     * @generated from protobuf rpc: GetMRRMetrics
     */
    getMRRMetrics(input: GetMRRMetricsRequest, options?: RpcOptions): UnaryCall<GetMRRMetricsRequest, GetMRRMetricsResponse>;
    /**
     * @generated from protobuf rpc: GetChurnMetrics
     */
    getChurnMetrics(input: GetChurnMetricsRequest, options?: RpcOptions): UnaryCall<GetChurnMetricsRequest, GetChurnMetricsResponse>;
    /**
     * @generated from protobuf rpc: GetRevenueMetrics
     */
    getRevenueMetrics(input: GetRevenueMetricsRequest, options?: RpcOptions): UnaryCall<GetRevenueMetricsRequest, GetRevenueMetricsResponse>;
    /**
     * @generated from protobuf rpc: GetCohortAnalysis
     */
    getCohortAnalysis(input: GetCohortAnalysisRequest, options?: RpcOptions): UnaryCall<GetCohortAnalysisRequest, GetCohortAnalysisResponse>;
    /**
     * @generated from protobuf rpc: ForecastRevenue
     */
    forecastRevenue(input: ForecastRevenueRequest, options?: RpcOptions): UnaryCall<ForecastRevenueRequest, ForecastRevenueResponse>;
    /**
     * @generated from protobuf rpc: GetUserAnalytics
     */
    getUserAnalytics(input: GetUserAnalyticsRequest, options?: RpcOptions): UnaryCall<GetUserAnalyticsRequest, GetUserAnalyticsResponse>;
    /**
     * Payment Method endpoints
     *
     * @generated from protobuf rpc: AddPaymentMethod
     */
    addPaymentMethod(input: AddPaymentMethodRequest, options?: RpcOptions): UnaryCall<AddPaymentMethodRequest, AddPaymentMethodResponse>;
    /**
     * @generated from protobuf rpc: GetPaymentMethods
     */
    getPaymentMethods(input: GetPaymentMethodsRequest, options?: RpcOptions): UnaryCall<GetPaymentMethodsRequest, GetPaymentMethodsResponse>;
    /**
     * @generated from protobuf rpc: GetDefaultPaymentMethod
     */
    getDefaultPaymentMethod(input: GetDefaultPaymentMethodRequest, options?: RpcOptions): UnaryCall<GetDefaultPaymentMethodRequest, GetDefaultPaymentMethodResponse>;
    /**
     * @generated from protobuf rpc: SetDefaultPaymentMethod
     */
    setDefaultPaymentMethod(input: SetDefaultPaymentMethodRequest, options?: RpcOptions): UnaryCall<SetDefaultPaymentMethodRequest, SetDefaultPaymentMethodResponse>;
    /**
     * @generated from protobuf rpc: RemovePaymentMethod
     */
    removePaymentMethod(input: RemovePaymentMethodRequest, options?: RpcOptions): UnaryCall<RemovePaymentMethodRequest, RemovePaymentMethodResponse>;
    /**
     * @generated from protobuf rpc: UpdatePaymentMethodNickname
     */
    updatePaymentMethodNickname(input: UpdatePaymentMethodNicknameRequest, options?: RpcOptions): UnaryCall<UpdatePaymentMethodNicknameRequest, UpdatePaymentMethodNicknameResponse>;
}
/**
 * Payments Service Definition
 *
 * @generated from protobuf service payments.PaymentsService
 */
export class PaymentsServiceClient implements IPaymentsServiceClient, ServiceInfo {
    typeName = PaymentsService.typeName;
    methods = PaymentsService.methods;
    options = PaymentsService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * Plan management
     *
     * @generated from protobuf rpc: GetPlans
     */
    getPlans(input: GetPlansRequest, options?: RpcOptions): UnaryCall<GetPlansRequest, GetPlansResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetPlansRequest, GetPlansResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetPlan
     */
    getPlan(input: GetPlanRequest, options?: RpcOptions): UnaryCall<GetPlanRequest, GetPlanResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetPlanRequest, GetPlanResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Subscription management
     *
     * @generated from protobuf rpc: CreateSubscription
     */
    createSubscription(input: CreateSubscriptionRequest, options?: RpcOptions): UnaryCall<CreateSubscriptionRequest, CreateSubscriptionResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreateSubscriptionRequest, CreateSubscriptionResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetSubscription
     */
    getSubscription(input: GetSubscriptionRequest, options?: RpcOptions): UnaryCall<GetSubscriptionRequest, GetSubscriptionResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetSubscriptionRequest, GetSubscriptionResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetMySubscription
     */
    getMySubscription(input: GetMySubscriptionRequest, options?: RpcOptions): UnaryCall<GetMySubscriptionRequest, GetMySubscriptionResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetMySubscriptionRequest, GetMySubscriptionResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListMySubscriptions
     */
    listMySubscriptions(input: ListMySubscriptionsRequest, options?: RpcOptions): UnaryCall<ListMySubscriptionsRequest, ListMySubscriptionsResponse> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListMySubscriptionsRequest, ListMySubscriptionsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CancelSubscription
     */
    cancelSubscription(input: CancelSubscriptionRequest, options?: RpcOptions): UnaryCall<CancelSubscriptionRequest, CancelSubscriptionResponse> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<CancelSubscriptionRequest, CancelSubscriptionResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CheckSubscriptionAccess
     */
    checkSubscriptionAccess(input: CheckSubscriptionAccessRequest, options?: RpcOptions): UnaryCall<CheckSubscriptionAccessRequest, CheckSubscriptionAccessResponse> {
        const method = this.methods[7], opt = this._transport.mergeOptions(options);
        return stackIntercept<CheckSubscriptionAccessRequest, CheckSubscriptionAccessResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Pause/Resume subscription
     *
     * @generated from protobuf rpc: PauseSubscription
     */
    pauseSubscription(input: PauseSubscriptionRequest, options?: RpcOptions): UnaryCall<PauseSubscriptionRequest, PauseSubscriptionResponse> {
        const method = this.methods[8], opt = this._transport.mergeOptions(options);
        return stackIntercept<PauseSubscriptionRequest, PauseSubscriptionResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ResumeSubscription
     */
    resumeSubscription(input: ResumeSubscriptionRequest, options?: RpcOptions): UnaryCall<ResumeSubscriptionRequest, ResumeSubscriptionResponse> {
        const method = this.methods[9], opt = this._transport.mergeOptions(options);
        return stackIntercept<ResumeSubscriptionRequest, ResumeSubscriptionResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetPauseStatus
     */
    getPauseStatus(input: GetPauseStatusRequest, options?: RpcOptions): UnaryCall<GetPauseStatusRequest, GetPauseStatusResponse> {
        const method = this.methods[10], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetPauseStatusRequest, GetPauseStatusResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Self-service cancellation
     *
     * @generated from protobuf rpc: InitiateCancellation
     */
    initiateCancellation(input: InitiateCancellationRequest, options?: RpcOptions): UnaryCall<InitiateCancellationRequest, InitiateCancellationResponse> {
        const method = this.methods[11], opt = this._transport.mergeOptions(options);
        return stackIntercept<InitiateCancellationRequest, InitiateCancellationResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: AcceptRetentionOffer
     */
    acceptRetentionOffer(input: AcceptRetentionOfferRequest, options?: RpcOptions): UnaryCall<AcceptRetentionOfferRequest, AcceptRetentionOfferResponse> {
        const method = this.methods[12], opt = this._transport.mergeOptions(options);
        return stackIntercept<AcceptRetentionOfferRequest, AcceptRetentionOfferResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ConfirmCancellation
     */
    confirmCancellation(input: ConfirmCancellationRequest, options?: RpcOptions): UnaryCall<ConfirmCancellationRequest, ConfirmCancellationResponse> {
        const method = this.methods[13], opt = this._transport.mergeOptions(options);
        return stackIntercept<ConfirmCancellationRequest, ConfirmCancellationResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UndoCancellation
     */
    undoCancellation(input: UndoCancellationRequest, options?: RpcOptions): UnaryCall<UndoCancellationRequest, UndoCancellationResponse> {
        const method = this.methods[14], opt = this._transport.mergeOptions(options);
        return stackIntercept<UndoCancellationRequest, UndoCancellationResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetCancellationStatus
     */
    getCancellationStatus(input: GetCancellationStatusRequest, options?: RpcOptions): UnaryCall<GetCancellationStatusRequest, GetCancellationStatusResponse> {
        const method = this.methods[15], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetCancellationStatusRequest, GetCancellationStatusResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Payment processing
     *
     * @generated from protobuf rpc: CreateSubscriptionCheckout
     */
    createSubscriptionCheckout(input: CreateSubscriptionCheckoutRequest, options?: RpcOptions): UnaryCall<CreateSubscriptionCheckoutRequest, CreateSubscriptionCheckoutResponse> {
        const method = this.methods[16], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreateSubscriptionCheckoutRequest, CreateSubscriptionCheckoutResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: InitiatePayment
     */
    initiatePayment(input: InitiatePaymentRequest, options?: RpcOptions): UnaryCall<InitiatePaymentRequest, InitiatePaymentResponse> {
        const method = this.methods[17], opt = this._transport.mergeOptions(options);
        return stackIntercept<InitiatePaymentRequest, InitiatePaymentResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetPayment
     */
    getPayment(input: GetPaymentRequest, options?: RpcOptions): UnaryCall<GetPaymentRequest, GetPaymentResponse> {
        const method = this.methods[18], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetPaymentRequest, GetPaymentResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListMyPayments
     */
    listMyPayments(input: ListMyPaymentsRequest, options?: RpcOptions): UnaryCall<ListMyPaymentsRequest, ListMyPaymentsResponse> {
        const method = this.methods[19], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListMyPaymentsRequest, ListMyPaymentsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CheckPaymentStatus
     */
    checkPaymentStatus(input: CheckPaymentStatusRequest, options?: RpcOptions): UnaryCall<CheckPaymentStatusRequest, CheckPaymentStatusResponse> {
        const method = this.methods[20], opt = this._transport.mergeOptions(options);
        return stackIntercept<CheckPaymentStatusRequest, CheckPaymentStatusResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DownloadReceipt
     */
    downloadReceipt(input: DownloadReceiptRequest, options?: RpcOptions): UnaryCall<DownloadReceiptRequest, DownloadReceiptResponse> {
        const method = this.methods[21], opt = this._transport.mergeOptions(options);
        return stackIntercept<DownloadReceiptRequest, DownloadReceiptResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: EmailReceipt
     */
    emailReceipt(input: EmailReceiptRequest, options?: RpcOptions): UnaryCall<EmailReceiptRequest, EmailReceiptResponse> {
        const method = this.methods[22], opt = this._transport.mergeOptions(options);
        return stackIntercept<EmailReceiptRequest, EmailReceiptResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Proration management
     *
     * @generated from protobuf rpc: PreviewProration
     */
    previewProration(input: PreviewProrationRequest, options?: RpcOptions): UnaryCall<PreviewProrationRequest, PreviewProrationResponse> {
        const method = this.methods[23], opt = this._transport.mergeOptions(options);
        return stackIntercept<PreviewProrationRequest, PreviewProrationResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ChangePlan
     */
    changePlan(input: ChangePlanRequest, options?: RpcOptions): UnaryCall<ChangePlanRequest, ChangePlanResponse> {
        const method = this.methods[24], opt = this._transport.mergeOptions(options);
        return stackIntercept<ChangePlanRequest, ChangePlanResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetProrationHistory
     */
    getProrationHistory(input: GetProrationHistoryRequest, options?: RpcOptions): UnaryCall<GetProrationHistoryRequest, GetProrationHistoryResponse> {
        const method = this.methods[25], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetProrationHistoryRequest, GetProrationHistoryResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetCreditBalance
     */
    getCreditBalance(input: GetCreditBalanceRequest, options?: RpcOptions): UnaryCall<GetCreditBalanceRequest, GetCreditBalanceResponse> {
        const method = this.methods[26], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetCreditBalanceRequest, GetCreditBalanceResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Fraud prevention admin
     *
     * @generated from protobuf rpc: GetFraudStats
     */
    getFraudStats(input: GetFraudStatsRequest, options?: RpcOptions): UnaryCall<GetFraudStatsRequest, GetFraudStatsResponse> {
        const method = this.methods[27], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetFraudStatsRequest, GetFraudStatsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetFlaggedUsers
     */
    getFlaggedUsers(input: GetFlaggedUsersRequest, options?: RpcOptions): UnaryCall<GetFlaggedUsersRequest, GetFlaggedUsersResponse> {
        const method = this.methods[28], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetFlaggedUsersRequest, GetFlaggedUsersResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetBlacklistedPhones
     */
    getBlacklistedPhones(input: GetBlacklistedPhonesRequest, options?: RpcOptions): UnaryCall<GetBlacklistedPhonesRequest, GetBlacklistedPhonesResponse> {
        const method = this.methods[29], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetBlacklistedPhonesRequest, GetBlacklistedPhonesResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetBlacklistedIPs
     */
    getBlacklistedIPs(input: GetBlacklistedIPsRequest, options?: RpcOptions): UnaryCall<GetBlacklistedIPsRequest, GetBlacklistedIPsResponse> {
        const method = this.methods[30], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetBlacklistedIPsRequest, GetBlacklistedIPsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: BlacklistPhone
     */
    blacklistPhone(input: BlacklistPhoneRequest, options?: RpcOptions): UnaryCall<BlacklistPhoneRequest, BlacklistPhoneResponse> {
        const method = this.methods[31], opt = this._transport.mergeOptions(options);
        return stackIntercept<BlacklistPhoneRequest, BlacklistPhoneResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: BlacklistIP
     */
    blacklistIP(input: BlacklistIPRequest, options?: RpcOptions): UnaryCall<BlacklistIPRequest, BlacklistIPResponse> {
        const method = this.methods[32], opt = this._transport.mergeOptions(options);
        return stackIntercept<BlacklistIPRequest, BlacklistIPResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: RemovePhoneFromBlacklist
     */
    removePhoneFromBlacklist(input: RemovePhoneFromBlacklistRequest, options?: RpcOptions): UnaryCall<RemovePhoneFromBlacklistRequest, RemovePhoneFromBlacklistResponse> {
        const method = this.methods[33], opt = this._transport.mergeOptions(options);
        return stackIntercept<RemovePhoneFromBlacklistRequest, RemovePhoneFromBlacklistResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: RemoveIPFromBlacklist
     */
    removeIPFromBlacklist(input: RemoveIPFromBlacklistRequest, options?: RpcOptions): UnaryCall<RemoveIPFromBlacklistRequest, RemoveIPFromBlacklistResponse> {
        const method = this.methods[34], opt = this._transport.mergeOptions(options);
        return stackIntercept<RemoveIPFromBlacklistRequest, RemoveIPFromBlacklistResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetFraudRules
     */
    getFraudRules(input: GetFraudRulesRequest, options?: RpcOptions): UnaryCall<GetFraudRulesRequest, GetFraudRulesResponse> {
        const method = this.methods[35], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetFraudRulesRequest, GetFraudRulesResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateFraudRule
     */
    updateFraudRule(input: UpdateFraudRuleRequest, options?: RpcOptions): UnaryCall<UpdateFraudRuleRequest, UpdateFraudRuleResponse> {
        const method = this.methods[36], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateFraudRuleRequest, UpdateFraudRuleResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Analytics endpoints
     *
     * @generated from protobuf rpc: GetAnalytics
     */
    getAnalytics(input: GetAnalyticsRequest, options?: RpcOptions): UnaryCall<GetAnalyticsRequest, GetAnalyticsResponse> {
        const method = this.methods[37], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetAnalyticsRequest, GetAnalyticsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetMRRMetrics
     */
    getMRRMetrics(input: GetMRRMetricsRequest, options?: RpcOptions): UnaryCall<GetMRRMetricsRequest, GetMRRMetricsResponse> {
        const method = this.methods[38], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetMRRMetricsRequest, GetMRRMetricsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetChurnMetrics
     */
    getChurnMetrics(input: GetChurnMetricsRequest, options?: RpcOptions): UnaryCall<GetChurnMetricsRequest, GetChurnMetricsResponse> {
        const method = this.methods[39], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetChurnMetricsRequest, GetChurnMetricsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetRevenueMetrics
     */
    getRevenueMetrics(input: GetRevenueMetricsRequest, options?: RpcOptions): UnaryCall<GetRevenueMetricsRequest, GetRevenueMetricsResponse> {
        const method = this.methods[40], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetRevenueMetricsRequest, GetRevenueMetricsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetCohortAnalysis
     */
    getCohortAnalysis(input: GetCohortAnalysisRequest, options?: RpcOptions): UnaryCall<GetCohortAnalysisRequest, GetCohortAnalysisResponse> {
        const method = this.methods[41], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetCohortAnalysisRequest, GetCohortAnalysisResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ForecastRevenue
     */
    forecastRevenue(input: ForecastRevenueRequest, options?: RpcOptions): UnaryCall<ForecastRevenueRequest, ForecastRevenueResponse> {
        const method = this.methods[42], opt = this._transport.mergeOptions(options);
        return stackIntercept<ForecastRevenueRequest, ForecastRevenueResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetUserAnalytics
     */
    getUserAnalytics(input: GetUserAnalyticsRequest, options?: RpcOptions): UnaryCall<GetUserAnalyticsRequest, GetUserAnalyticsResponse> {
        const method = this.methods[43], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetUserAnalyticsRequest, GetUserAnalyticsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Payment Method endpoints
     *
     * @generated from protobuf rpc: AddPaymentMethod
     */
    addPaymentMethod(input: AddPaymentMethodRequest, options?: RpcOptions): UnaryCall<AddPaymentMethodRequest, AddPaymentMethodResponse> {
        const method = this.methods[44], opt = this._transport.mergeOptions(options);
        return stackIntercept<AddPaymentMethodRequest, AddPaymentMethodResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetPaymentMethods
     */
    getPaymentMethods(input: GetPaymentMethodsRequest, options?: RpcOptions): UnaryCall<GetPaymentMethodsRequest, GetPaymentMethodsResponse> {
        const method = this.methods[45], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetPaymentMethodsRequest, GetPaymentMethodsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetDefaultPaymentMethod
     */
    getDefaultPaymentMethod(input: GetDefaultPaymentMethodRequest, options?: RpcOptions): UnaryCall<GetDefaultPaymentMethodRequest, GetDefaultPaymentMethodResponse> {
        const method = this.methods[46], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetDefaultPaymentMethodRequest, GetDefaultPaymentMethodResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SetDefaultPaymentMethod
     */
    setDefaultPaymentMethod(input: SetDefaultPaymentMethodRequest, options?: RpcOptions): UnaryCall<SetDefaultPaymentMethodRequest, SetDefaultPaymentMethodResponse> {
        const method = this.methods[47], opt = this._transport.mergeOptions(options);
        return stackIntercept<SetDefaultPaymentMethodRequest, SetDefaultPaymentMethodResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: RemovePaymentMethod
     */
    removePaymentMethod(input: RemovePaymentMethodRequest, options?: RpcOptions): UnaryCall<RemovePaymentMethodRequest, RemovePaymentMethodResponse> {
        const method = this.methods[48], opt = this._transport.mergeOptions(options);
        return stackIntercept<RemovePaymentMethodRequest, RemovePaymentMethodResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdatePaymentMethodNickname
     */
    updatePaymentMethodNickname(input: UpdatePaymentMethodNicknameRequest, options?: RpcOptions): UnaryCall<UpdatePaymentMethodNicknameRequest, UpdatePaymentMethodNicknameResponse> {
        const method = this.methods[49], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdatePaymentMethodNicknameRequest, UpdatePaymentMethodNicknameResponse>("unary", this._transport, method, opt, input);
    }
}
