// @generated by protobuf-ts 2.11.1 with parameter long_type_string
// @generated from protobuf file "auth/device.proto" (package "auth", syntax proto3)
// tslint:disable
import { Empty } from "../google/protobuf/empty";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Timestamp } from "../google/protobuf/timestamp";
// ═════════════════════════════════════════════════════════════
// DEVICE MESSAGES
// ═════════════════════════════════════════════════════════════

/**
 * @generated from protobuf message auth.Device
 */
export interface Device {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: string user_id = 2
     */
    userId: string;
    /**
     * @generated from protobuf field: string device_id = 3
     */
    deviceId: string;
    /**
     * @generated from protobuf field: string device_name = 4
     */
    deviceName: string;
    /**
     * @generated from protobuf field: string device_type = 5
     */
    deviceType: string; // mobile, tablet, desktop, unknown
    /**
     * @generated from protobuf field: string status = 6
     */
    status: string; // pending, active, revoked, expired, suspicious
    /**
     * Device Information
     *
     * @generated from protobuf field: string user_agent = 7
     */
    userAgent: string;
    /**
     * @generated from protobuf field: string browser = 8
     */
    browser: string;
    /**
     * @generated from protobuf field: string browser_version = 9
     */
    browserVersion: string;
    /**
     * @generated from protobuf field: string os = 10
     */
    os: string;
    /**
     * @generated from protobuf field: string os_version = 11
     */
    osVersion: string;
    /**
     * @generated from protobuf field: string platform = 12
     */
    platform: string;
    /**
     * Location Information
     *
     * @generated from protobuf field: string ip_address = 13
     */
    ipAddress: string;
    /**
     * @generated from protobuf field: string country = 14
     */
    country: string;
    /**
     * @generated from protobuf field: string city = 15
     */
    city: string;
    /**
     * @generated from protobuf field: string region = 16
     */
    region: string;
    /**
     * @generated from protobuf field: string timezone = 17
     */
    timezone: string;
    /**
     * @generated from protobuf field: double latitude = 18
     */
    latitude: number;
    /**
     * @generated from protobuf field: double longitude = 19
     */
    longitude: number;
    /**
     * Security
     *
     * @generated from protobuf field: google.protobuf.Timestamp confirmed_at = 20
     */
    confirmedAt?: Timestamp;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp last_activity_at = 21
     */
    lastActivityAt?: Timestamp;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp expires_at = 22
     */
    expiresAt?: Timestamp;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp revoked_at = 23
     */
    revokedAt?: Timestamp;
    /**
     * @generated from protobuf field: string revoked_reason = 24
     */
    revokedReason: string;
    /**
     * Metadata
     *
     * @generated from protobuf field: bool is_trusted = 25
     */
    isTrusted: boolean;
    /**
     * @generated from protobuf field: bool is_current_device = 26
     */
    isCurrentDevice: boolean;
    /**
     * @generated from protobuf field: int32 login_count = 27
     */
    loginCount: number;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp created_at = 28
     */
    createdAt?: Timestamp;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp updated_at = 29
     */
    updatedAt?: Timestamp;
}
/**
 * @generated from protobuf message auth.RegisterDeviceRequest
 */
export interface RegisterDeviceRequest {
    /**
     * @generated from protobuf field: string user_id = 1
     */
    userId: string;
    /**
     * @generated from protobuf field: string device_id = 2
     */
    deviceId: string;
    /**
     * @generated from protobuf field: string device_name = 3
     */
    deviceName: string;
    /**
     * @generated from protobuf field: string user_agent = 4
     */
    userAgent: string;
    /**
     * @generated from protobuf field: string ip_address = 5
     */
    ipAddress: string;
    /**
     * @generated from protobuf field: double latitude = 6
     */
    latitude: number;
    /**
     * @generated from protobuf field: double longitude = 7
     */
    longitude: number;
}
/**
 * @generated from protobuf message auth.RegisterDeviceResponse
 */
export interface RegisterDeviceResponse {
    /**
     * @generated from protobuf field: string message = 1
     */
    message: string;
    /**
     * @generated from protobuf field: auth.Device device = 2
     */
    device?: Device;
    /**
     * @generated from protobuf field: bool requires_confirmation = 3
     */
    requiresConfirmation: boolean;
}
/**
 * @generated from protobuf message auth.ConfirmDeviceRequest
 */
export interface ConfirmDeviceRequest {
    /**
     * @generated from protobuf field: string token = 1
     */
    token: string;
}
/**
 * @generated from protobuf message auth.ConfirmDeviceResponse
 */
export interface ConfirmDeviceResponse {
    /**
     * @generated from protobuf field: string message = 1
     */
    message: string;
    /**
     * @generated from protobuf field: auth.Device device = 2
     */
    device?: Device;
}
/**
 * @generated from protobuf message auth.GetUserDevicesRequest
 */
export interface GetUserDevicesRequest {
    /**
     * @generated from protobuf field: string user_id = 1
     */
    userId: string;
    /**
     * @generated from protobuf field: string current_device_id = 2
     */
    currentDeviceId: string; // Optional: to mark current device
}
/**
 * @generated from protobuf message auth.GetUserDevicesResponse
 */
export interface GetUserDevicesResponse {
    /**
     * @generated from protobuf field: repeated auth.Device devices = 1
     */
    devices: Device[];
    /**
     * @generated from protobuf field: int32 total_count = 2
     */
    totalCount: number;
    /**
     * @generated from protobuf field: int32 active_count = 3
     */
    activeCount: number;
    /**
     * @generated from protobuf field: int32 pending_count = 4
     */
    pendingCount: number;
}
/**
 * @generated from protobuf message auth.GetDeviceRequest
 */
export interface GetDeviceRequest {
    /**
     * @generated from protobuf field: string device_id = 1
     */
    deviceId: string;
    /**
     * @generated from protobuf field: string user_id = 2
     */
    userId: string;
}
/**
 * @generated from protobuf message auth.RevokeDeviceRequest
 */
export interface RevokeDeviceRequest {
    /**
     * @generated from protobuf field: string device_id = 1
     */
    deviceId: string;
    /**
     * @generated from protobuf field: string user_id = 2
     */
    userId: string;
    /**
     * @generated from protobuf field: string reason = 3
     */
    reason: string;
}
/**
 * @generated from protobuf message auth.RevokeAllDevicesRequest
 */
export interface RevokeAllDevicesRequest {
    /**
     * @generated from protobuf field: string user_id = 1
     */
    userId: string;
    /**
     * @generated from protobuf field: string except_device_id = 2
     */
    exceptDeviceId: string; // Optional: keep current device active
    /**
     * @generated from protobuf field: string reason = 3
     */
    reason: string;
}
/**
 * @generated from protobuf message auth.DeviceActivityLog
 */
export interface DeviceActivityLog {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: string device_id = 2
     */
    deviceId: string;
    /**
     * @generated from protobuf field: string user_id = 3
     */
    userId: string;
    /**
     * @generated from protobuf field: string action = 4
     */
    action: string;
    /**
     * @generated from protobuf field: string ip_address = 5
     */
    ipAddress: string;
    /**
     * @generated from protobuf field: string user_agent = 6
     */
    userAgent: string;
    /**
     * @generated from protobuf field: string metadata = 7
     */
    metadata: string; // JSON string
    /**
     * @generated from protobuf field: google.protobuf.Timestamp created_at = 8
     */
    createdAt?: Timestamp;
}
/**
 * @generated from protobuf message auth.GetDeviceActivityRequest
 */
export interface GetDeviceActivityRequest {
    /**
     * @generated from protobuf field: string device_id = 1
     */
    deviceId: string;
    /**
     * @generated from protobuf field: string user_id = 2
     */
    userId: string;
    /**
     * @generated from protobuf field: int32 limit = 3
     */
    limit: number;
}
/**
 * @generated from protobuf message auth.GetDeviceActivityResponse
 */
export interface GetDeviceActivityResponse {
    /**
     * @generated from protobuf field: repeated auth.DeviceActivityLog logs = 1
     */
    logs: DeviceActivityLog[];
    /**
     * @generated from protobuf field: int32 count = 2
     */
    count: number;
}
/**
 * @generated from protobuf message auth.UpdateDeviceActivityRequest
 */
export interface UpdateDeviceActivityRequest {
    /**
     * @generated from protobuf field: string device_id = 1
     */
    deviceId: string;
    /**
     * @generated from protobuf field: string user_id = 2
     */
    userId: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class Device$Type extends MessageType<Device> {
    constructor() {
        super("auth.Device", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "user_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "device_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "device_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "device_type", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "status", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "user_agent", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "browser", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 9, name: "browser_version", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 10, name: "os", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 11, name: "os_version", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 12, name: "platform", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 13, name: "ip_address", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 14, name: "country", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 15, name: "city", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 16, name: "region", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 17, name: "timezone", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 18, name: "latitude", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 19, name: "longitude", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 20, name: "confirmed_at", kind: "message", T: () => Timestamp },
            { no: 21, name: "last_activity_at", kind: "message", T: () => Timestamp },
            { no: 22, name: "expires_at", kind: "message", T: () => Timestamp },
            { no: 23, name: "revoked_at", kind: "message", T: () => Timestamp },
            { no: 24, name: "revoked_reason", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 25, name: "is_trusted", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 26, name: "is_current_device", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 27, name: "login_count", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 28, name: "created_at", kind: "message", T: () => Timestamp },
            { no: 29, name: "updated_at", kind: "message", T: () => Timestamp }
        ]);
    }
    create(value?: PartialMessage<Device>): Device {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.userId = "";
        message.deviceId = "";
        message.deviceName = "";
        message.deviceType = "";
        message.status = "";
        message.userAgent = "";
        message.browser = "";
        message.browserVersion = "";
        message.os = "";
        message.osVersion = "";
        message.platform = "";
        message.ipAddress = "";
        message.country = "";
        message.city = "";
        message.region = "";
        message.timezone = "";
        message.latitude = 0;
        message.longitude = 0;
        message.revokedReason = "";
        message.isTrusted = false;
        message.isCurrentDevice = false;
        message.loginCount = 0;
        if (value !== undefined)
            reflectionMergePartial<Device>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Device): Device {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* string user_id */ 2:
                    message.userId = reader.string();
                    break;
                case /* string device_id */ 3:
                    message.deviceId = reader.string();
                    break;
                case /* string device_name */ 4:
                    message.deviceName = reader.string();
                    break;
                case /* string device_type */ 5:
                    message.deviceType = reader.string();
                    break;
                case /* string status */ 6:
                    message.status = reader.string();
                    break;
                case /* string user_agent */ 7:
                    message.userAgent = reader.string();
                    break;
                case /* string browser */ 8:
                    message.browser = reader.string();
                    break;
                case /* string browser_version */ 9:
                    message.browserVersion = reader.string();
                    break;
                case /* string os */ 10:
                    message.os = reader.string();
                    break;
                case /* string os_version */ 11:
                    message.osVersion = reader.string();
                    break;
                case /* string platform */ 12:
                    message.platform = reader.string();
                    break;
                case /* string ip_address */ 13:
                    message.ipAddress = reader.string();
                    break;
                case /* string country */ 14:
                    message.country = reader.string();
                    break;
                case /* string city */ 15:
                    message.city = reader.string();
                    break;
                case /* string region */ 16:
                    message.region = reader.string();
                    break;
                case /* string timezone */ 17:
                    message.timezone = reader.string();
                    break;
                case /* double latitude */ 18:
                    message.latitude = reader.double();
                    break;
                case /* double longitude */ 19:
                    message.longitude = reader.double();
                    break;
                case /* google.protobuf.Timestamp confirmed_at */ 20:
                    message.confirmedAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.confirmedAt);
                    break;
                case /* google.protobuf.Timestamp last_activity_at */ 21:
                    message.lastActivityAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.lastActivityAt);
                    break;
                case /* google.protobuf.Timestamp expires_at */ 22:
                    message.expiresAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.expiresAt);
                    break;
                case /* google.protobuf.Timestamp revoked_at */ 23:
                    message.revokedAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.revokedAt);
                    break;
                case /* string revoked_reason */ 24:
                    message.revokedReason = reader.string();
                    break;
                case /* bool is_trusted */ 25:
                    message.isTrusted = reader.bool();
                    break;
                case /* bool is_current_device */ 26:
                    message.isCurrentDevice = reader.bool();
                    break;
                case /* int32 login_count */ 27:
                    message.loginCount = reader.int32();
                    break;
                case /* google.protobuf.Timestamp created_at */ 28:
                    message.createdAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.createdAt);
                    break;
                case /* google.protobuf.Timestamp updated_at */ 29:
                    message.updatedAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.updatedAt);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Device, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* string user_id = 2; */
        if (message.userId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.userId);
        /* string device_id = 3; */
        if (message.deviceId !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.deviceId);
        /* string device_name = 4; */
        if (message.deviceName !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.deviceName);
        /* string device_type = 5; */
        if (message.deviceType !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.deviceType);
        /* string status = 6; */
        if (message.status !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.status);
        /* string user_agent = 7; */
        if (message.userAgent !== "")
            writer.tag(7, WireType.LengthDelimited).string(message.userAgent);
        /* string browser = 8; */
        if (message.browser !== "")
            writer.tag(8, WireType.LengthDelimited).string(message.browser);
        /* string browser_version = 9; */
        if (message.browserVersion !== "")
            writer.tag(9, WireType.LengthDelimited).string(message.browserVersion);
        /* string os = 10; */
        if (message.os !== "")
            writer.tag(10, WireType.LengthDelimited).string(message.os);
        /* string os_version = 11; */
        if (message.osVersion !== "")
            writer.tag(11, WireType.LengthDelimited).string(message.osVersion);
        /* string platform = 12; */
        if (message.platform !== "")
            writer.tag(12, WireType.LengthDelimited).string(message.platform);
        /* string ip_address = 13; */
        if (message.ipAddress !== "")
            writer.tag(13, WireType.LengthDelimited).string(message.ipAddress);
        /* string country = 14; */
        if (message.country !== "")
            writer.tag(14, WireType.LengthDelimited).string(message.country);
        /* string city = 15; */
        if (message.city !== "")
            writer.tag(15, WireType.LengthDelimited).string(message.city);
        /* string region = 16; */
        if (message.region !== "")
            writer.tag(16, WireType.LengthDelimited).string(message.region);
        /* string timezone = 17; */
        if (message.timezone !== "")
            writer.tag(17, WireType.LengthDelimited).string(message.timezone);
        /* double latitude = 18; */
        if (message.latitude !== 0)
            writer.tag(18, WireType.Bit64).double(message.latitude);
        /* double longitude = 19; */
        if (message.longitude !== 0)
            writer.tag(19, WireType.Bit64).double(message.longitude);
        /* google.protobuf.Timestamp confirmed_at = 20; */
        if (message.confirmedAt)
            Timestamp.internalBinaryWrite(message.confirmedAt, writer.tag(20, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Timestamp last_activity_at = 21; */
        if (message.lastActivityAt)
            Timestamp.internalBinaryWrite(message.lastActivityAt, writer.tag(21, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Timestamp expires_at = 22; */
        if (message.expiresAt)
            Timestamp.internalBinaryWrite(message.expiresAt, writer.tag(22, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Timestamp revoked_at = 23; */
        if (message.revokedAt)
            Timestamp.internalBinaryWrite(message.revokedAt, writer.tag(23, WireType.LengthDelimited).fork(), options).join();
        /* string revoked_reason = 24; */
        if (message.revokedReason !== "")
            writer.tag(24, WireType.LengthDelimited).string(message.revokedReason);
        /* bool is_trusted = 25; */
        if (message.isTrusted !== false)
            writer.tag(25, WireType.Varint).bool(message.isTrusted);
        /* bool is_current_device = 26; */
        if (message.isCurrentDevice !== false)
            writer.tag(26, WireType.Varint).bool(message.isCurrentDevice);
        /* int32 login_count = 27; */
        if (message.loginCount !== 0)
            writer.tag(27, WireType.Varint).int32(message.loginCount);
        /* google.protobuf.Timestamp created_at = 28; */
        if (message.createdAt)
            Timestamp.internalBinaryWrite(message.createdAt, writer.tag(28, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Timestamp updated_at = 29; */
        if (message.updatedAt)
            Timestamp.internalBinaryWrite(message.updatedAt, writer.tag(29, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message auth.Device
 */
export const Device = new Device$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RegisterDeviceRequest$Type extends MessageType<RegisterDeviceRequest> {
    constructor() {
        super("auth.RegisterDeviceRequest", [
            { no: 1, name: "user_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "device_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "device_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "user_agent", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "ip_address", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "latitude", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 7, name: "longitude", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ }
        ]);
    }
    create(value?: PartialMessage<RegisterDeviceRequest>): RegisterDeviceRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.userId = "";
        message.deviceId = "";
        message.deviceName = "";
        message.userAgent = "";
        message.ipAddress = "";
        message.latitude = 0;
        message.longitude = 0;
        if (value !== undefined)
            reflectionMergePartial<RegisterDeviceRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RegisterDeviceRequest): RegisterDeviceRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string user_id */ 1:
                    message.userId = reader.string();
                    break;
                case /* string device_id */ 2:
                    message.deviceId = reader.string();
                    break;
                case /* string device_name */ 3:
                    message.deviceName = reader.string();
                    break;
                case /* string user_agent */ 4:
                    message.userAgent = reader.string();
                    break;
                case /* string ip_address */ 5:
                    message.ipAddress = reader.string();
                    break;
                case /* double latitude */ 6:
                    message.latitude = reader.double();
                    break;
                case /* double longitude */ 7:
                    message.longitude = reader.double();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RegisterDeviceRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string user_id = 1; */
        if (message.userId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.userId);
        /* string device_id = 2; */
        if (message.deviceId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.deviceId);
        /* string device_name = 3; */
        if (message.deviceName !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.deviceName);
        /* string user_agent = 4; */
        if (message.userAgent !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.userAgent);
        /* string ip_address = 5; */
        if (message.ipAddress !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.ipAddress);
        /* double latitude = 6; */
        if (message.latitude !== 0)
            writer.tag(6, WireType.Bit64).double(message.latitude);
        /* double longitude = 7; */
        if (message.longitude !== 0)
            writer.tag(7, WireType.Bit64).double(message.longitude);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message auth.RegisterDeviceRequest
 */
export const RegisterDeviceRequest = new RegisterDeviceRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RegisterDeviceResponse$Type extends MessageType<RegisterDeviceResponse> {
    constructor() {
        super("auth.RegisterDeviceResponse", [
            { no: 1, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "device", kind: "message", T: () => Device },
            { no: 3, name: "requires_confirmation", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<RegisterDeviceResponse>): RegisterDeviceResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.message = "";
        message.requiresConfirmation = false;
        if (value !== undefined)
            reflectionMergePartial<RegisterDeviceResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RegisterDeviceResponse): RegisterDeviceResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string message */ 1:
                    message.message = reader.string();
                    break;
                case /* auth.Device device */ 2:
                    message.device = Device.internalBinaryRead(reader, reader.uint32(), options, message.device);
                    break;
                case /* bool requires_confirmation */ 3:
                    message.requiresConfirmation = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RegisterDeviceResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string message = 1; */
        if (message.message !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.message);
        /* auth.Device device = 2; */
        if (message.device)
            Device.internalBinaryWrite(message.device, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* bool requires_confirmation = 3; */
        if (message.requiresConfirmation !== false)
            writer.tag(3, WireType.Varint).bool(message.requiresConfirmation);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message auth.RegisterDeviceResponse
 */
export const RegisterDeviceResponse = new RegisterDeviceResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ConfirmDeviceRequest$Type extends MessageType<ConfirmDeviceRequest> {
    constructor() {
        super("auth.ConfirmDeviceRequest", [
            { no: 1, name: "token", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ConfirmDeviceRequest>): ConfirmDeviceRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.token = "";
        if (value !== undefined)
            reflectionMergePartial<ConfirmDeviceRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ConfirmDeviceRequest): ConfirmDeviceRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string token */ 1:
                    message.token = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ConfirmDeviceRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string token = 1; */
        if (message.token !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.token);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message auth.ConfirmDeviceRequest
 */
export const ConfirmDeviceRequest = new ConfirmDeviceRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ConfirmDeviceResponse$Type extends MessageType<ConfirmDeviceResponse> {
    constructor() {
        super("auth.ConfirmDeviceResponse", [
            { no: 1, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "device", kind: "message", T: () => Device }
        ]);
    }
    create(value?: PartialMessage<ConfirmDeviceResponse>): ConfirmDeviceResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.message = "";
        if (value !== undefined)
            reflectionMergePartial<ConfirmDeviceResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ConfirmDeviceResponse): ConfirmDeviceResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string message */ 1:
                    message.message = reader.string();
                    break;
                case /* auth.Device device */ 2:
                    message.device = Device.internalBinaryRead(reader, reader.uint32(), options, message.device);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ConfirmDeviceResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string message = 1; */
        if (message.message !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.message);
        /* auth.Device device = 2; */
        if (message.device)
            Device.internalBinaryWrite(message.device, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message auth.ConfirmDeviceResponse
 */
export const ConfirmDeviceResponse = new ConfirmDeviceResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetUserDevicesRequest$Type extends MessageType<GetUserDevicesRequest> {
    constructor() {
        super("auth.GetUserDevicesRequest", [
            { no: 1, name: "user_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "current_device_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetUserDevicesRequest>): GetUserDevicesRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.userId = "";
        message.currentDeviceId = "";
        if (value !== undefined)
            reflectionMergePartial<GetUserDevicesRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetUserDevicesRequest): GetUserDevicesRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string user_id */ 1:
                    message.userId = reader.string();
                    break;
                case /* string current_device_id */ 2:
                    message.currentDeviceId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetUserDevicesRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string user_id = 1; */
        if (message.userId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.userId);
        /* string current_device_id = 2; */
        if (message.currentDeviceId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.currentDeviceId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message auth.GetUserDevicesRequest
 */
export const GetUserDevicesRequest = new GetUserDevicesRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetUserDevicesResponse$Type extends MessageType<GetUserDevicesResponse> {
    constructor() {
        super("auth.GetUserDevicesResponse", [
            { no: 1, name: "devices", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Device },
            { no: 2, name: "total_count", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "active_count", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "pending_count", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<GetUserDevicesResponse>): GetUserDevicesResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.devices = [];
        message.totalCount = 0;
        message.activeCount = 0;
        message.pendingCount = 0;
        if (value !== undefined)
            reflectionMergePartial<GetUserDevicesResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetUserDevicesResponse): GetUserDevicesResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated auth.Device devices */ 1:
                    message.devices.push(Device.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* int32 total_count */ 2:
                    message.totalCount = reader.int32();
                    break;
                case /* int32 active_count */ 3:
                    message.activeCount = reader.int32();
                    break;
                case /* int32 pending_count */ 4:
                    message.pendingCount = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetUserDevicesResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated auth.Device devices = 1; */
        for (let i = 0; i < message.devices.length; i++)
            Device.internalBinaryWrite(message.devices[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* int32 total_count = 2; */
        if (message.totalCount !== 0)
            writer.tag(2, WireType.Varint).int32(message.totalCount);
        /* int32 active_count = 3; */
        if (message.activeCount !== 0)
            writer.tag(3, WireType.Varint).int32(message.activeCount);
        /* int32 pending_count = 4; */
        if (message.pendingCount !== 0)
            writer.tag(4, WireType.Varint).int32(message.pendingCount);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message auth.GetUserDevicesResponse
 */
export const GetUserDevicesResponse = new GetUserDevicesResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetDeviceRequest$Type extends MessageType<GetDeviceRequest> {
    constructor() {
        super("auth.GetDeviceRequest", [
            { no: 1, name: "device_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "user_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetDeviceRequest>): GetDeviceRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.deviceId = "";
        message.userId = "";
        if (value !== undefined)
            reflectionMergePartial<GetDeviceRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetDeviceRequest): GetDeviceRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string device_id */ 1:
                    message.deviceId = reader.string();
                    break;
                case /* string user_id */ 2:
                    message.userId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetDeviceRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string device_id = 1; */
        if (message.deviceId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.deviceId);
        /* string user_id = 2; */
        if (message.userId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.userId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message auth.GetDeviceRequest
 */
export const GetDeviceRequest = new GetDeviceRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RevokeDeviceRequest$Type extends MessageType<RevokeDeviceRequest> {
    constructor() {
        super("auth.RevokeDeviceRequest", [
            { no: 1, name: "device_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "user_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "reason", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<RevokeDeviceRequest>): RevokeDeviceRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.deviceId = "";
        message.userId = "";
        message.reason = "";
        if (value !== undefined)
            reflectionMergePartial<RevokeDeviceRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RevokeDeviceRequest): RevokeDeviceRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string device_id */ 1:
                    message.deviceId = reader.string();
                    break;
                case /* string user_id */ 2:
                    message.userId = reader.string();
                    break;
                case /* string reason */ 3:
                    message.reason = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RevokeDeviceRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string device_id = 1; */
        if (message.deviceId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.deviceId);
        /* string user_id = 2; */
        if (message.userId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.userId);
        /* string reason = 3; */
        if (message.reason !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.reason);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message auth.RevokeDeviceRequest
 */
export const RevokeDeviceRequest = new RevokeDeviceRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RevokeAllDevicesRequest$Type extends MessageType<RevokeAllDevicesRequest> {
    constructor() {
        super("auth.RevokeAllDevicesRequest", [
            { no: 1, name: "user_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "except_device_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "reason", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<RevokeAllDevicesRequest>): RevokeAllDevicesRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.userId = "";
        message.exceptDeviceId = "";
        message.reason = "";
        if (value !== undefined)
            reflectionMergePartial<RevokeAllDevicesRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RevokeAllDevicesRequest): RevokeAllDevicesRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string user_id */ 1:
                    message.userId = reader.string();
                    break;
                case /* string except_device_id */ 2:
                    message.exceptDeviceId = reader.string();
                    break;
                case /* string reason */ 3:
                    message.reason = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RevokeAllDevicesRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string user_id = 1; */
        if (message.userId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.userId);
        /* string except_device_id = 2; */
        if (message.exceptDeviceId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.exceptDeviceId);
        /* string reason = 3; */
        if (message.reason !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.reason);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message auth.RevokeAllDevicesRequest
 */
export const RevokeAllDevicesRequest = new RevokeAllDevicesRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeviceActivityLog$Type extends MessageType<DeviceActivityLog> {
    constructor() {
        super("auth.DeviceActivityLog", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "device_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "user_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "action", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "ip_address", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "user_agent", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "metadata", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "created_at", kind: "message", T: () => Timestamp }
        ]);
    }
    create(value?: PartialMessage<DeviceActivityLog>): DeviceActivityLog {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.deviceId = "";
        message.userId = "";
        message.action = "";
        message.ipAddress = "";
        message.userAgent = "";
        message.metadata = "";
        if (value !== undefined)
            reflectionMergePartial<DeviceActivityLog>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DeviceActivityLog): DeviceActivityLog {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* string device_id */ 2:
                    message.deviceId = reader.string();
                    break;
                case /* string user_id */ 3:
                    message.userId = reader.string();
                    break;
                case /* string action */ 4:
                    message.action = reader.string();
                    break;
                case /* string ip_address */ 5:
                    message.ipAddress = reader.string();
                    break;
                case /* string user_agent */ 6:
                    message.userAgent = reader.string();
                    break;
                case /* string metadata */ 7:
                    message.metadata = reader.string();
                    break;
                case /* google.protobuf.Timestamp created_at */ 8:
                    message.createdAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.createdAt);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DeviceActivityLog, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* string device_id = 2; */
        if (message.deviceId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.deviceId);
        /* string user_id = 3; */
        if (message.userId !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.userId);
        /* string action = 4; */
        if (message.action !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.action);
        /* string ip_address = 5; */
        if (message.ipAddress !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.ipAddress);
        /* string user_agent = 6; */
        if (message.userAgent !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.userAgent);
        /* string metadata = 7; */
        if (message.metadata !== "")
            writer.tag(7, WireType.LengthDelimited).string(message.metadata);
        /* google.protobuf.Timestamp created_at = 8; */
        if (message.createdAt)
            Timestamp.internalBinaryWrite(message.createdAt, writer.tag(8, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message auth.DeviceActivityLog
 */
export const DeviceActivityLog = new DeviceActivityLog$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetDeviceActivityRequest$Type extends MessageType<GetDeviceActivityRequest> {
    constructor() {
        super("auth.GetDeviceActivityRequest", [
            { no: 1, name: "device_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "user_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "limit", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<GetDeviceActivityRequest>): GetDeviceActivityRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.deviceId = "";
        message.userId = "";
        message.limit = 0;
        if (value !== undefined)
            reflectionMergePartial<GetDeviceActivityRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetDeviceActivityRequest): GetDeviceActivityRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string device_id */ 1:
                    message.deviceId = reader.string();
                    break;
                case /* string user_id */ 2:
                    message.userId = reader.string();
                    break;
                case /* int32 limit */ 3:
                    message.limit = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetDeviceActivityRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string device_id = 1; */
        if (message.deviceId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.deviceId);
        /* string user_id = 2; */
        if (message.userId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.userId);
        /* int32 limit = 3; */
        if (message.limit !== 0)
            writer.tag(3, WireType.Varint).int32(message.limit);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message auth.GetDeviceActivityRequest
 */
export const GetDeviceActivityRequest = new GetDeviceActivityRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetDeviceActivityResponse$Type extends MessageType<GetDeviceActivityResponse> {
    constructor() {
        super("auth.GetDeviceActivityResponse", [
            { no: 1, name: "logs", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => DeviceActivityLog },
            { no: 2, name: "count", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<GetDeviceActivityResponse>): GetDeviceActivityResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.logs = [];
        message.count = 0;
        if (value !== undefined)
            reflectionMergePartial<GetDeviceActivityResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetDeviceActivityResponse): GetDeviceActivityResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated auth.DeviceActivityLog logs */ 1:
                    message.logs.push(DeviceActivityLog.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* int32 count */ 2:
                    message.count = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetDeviceActivityResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated auth.DeviceActivityLog logs = 1; */
        for (let i = 0; i < message.logs.length; i++)
            DeviceActivityLog.internalBinaryWrite(message.logs[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* int32 count = 2; */
        if (message.count !== 0)
            writer.tag(2, WireType.Varint).int32(message.count);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message auth.GetDeviceActivityResponse
 */
export const GetDeviceActivityResponse = new GetDeviceActivityResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdateDeviceActivityRequest$Type extends MessageType<UpdateDeviceActivityRequest> {
    constructor() {
        super("auth.UpdateDeviceActivityRequest", [
            { no: 1, name: "device_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "user_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<UpdateDeviceActivityRequest>): UpdateDeviceActivityRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.deviceId = "";
        message.userId = "";
        if (value !== undefined)
            reflectionMergePartial<UpdateDeviceActivityRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UpdateDeviceActivityRequest): UpdateDeviceActivityRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string device_id */ 1:
                    message.deviceId = reader.string();
                    break;
                case /* string user_id */ 2:
                    message.userId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UpdateDeviceActivityRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string device_id = 1; */
        if (message.deviceId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.deviceId);
        /* string user_id = 2; */
        if (message.userId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.userId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message auth.UpdateDeviceActivityRequest
 */
export const UpdateDeviceActivityRequest = new UpdateDeviceActivityRequest$Type();
/**
 * @generated ServiceType for protobuf service auth.DeviceService
 */
export const DeviceService = new ServiceType("auth.DeviceService", [
    { name: "RegisterDevice", options: {}, I: RegisterDeviceRequest, O: RegisterDeviceResponse },
    { name: "ConfirmDevice", options: {}, I: ConfirmDeviceRequest, O: ConfirmDeviceResponse },
    { name: "GetUserDevices", options: {}, I: GetUserDevicesRequest, O: GetUserDevicesResponse },
    { name: "GetDevice", options: {}, I: GetDeviceRequest, O: Device },
    { name: "RevokeDevice", options: {}, I: RevokeDeviceRequest, O: Empty },
    { name: "RevokeAllDevices", options: {}, I: RevokeAllDevicesRequest, O: Empty },
    { name: "GetDeviceActivity", options: {}, I: GetDeviceActivityRequest, O: GetDeviceActivityResponse },
    { name: "UpdateDeviceActivity", options: {}, I: UpdateDeviceActivityRequest, O: Empty }
]);
