// @generated by protobuf-ts 2.11.1 with parameter long_type_string
// @generated from protobuf file "auth/device.proto" (package "auth", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { DeviceService } from "./device";
import type { UpdateDeviceActivityRequest } from "./device";
import type { GetDeviceActivityResponse } from "./device";
import type { GetDeviceActivityRequest } from "./device";
import type { RevokeAllDevicesRequest } from "./device";
import type { Empty } from "../google/protobuf/empty";
import type { RevokeDeviceRequest } from "./device";
import type { Device } from "./device";
import type { GetDeviceRequest } from "./device";
import type { GetUserDevicesResponse } from "./device";
import type { GetUserDevicesRequest } from "./device";
import type { ConfirmDeviceResponse } from "./device";
import type { ConfirmDeviceRequest } from "./device";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { RegisterDeviceResponse } from "./device";
import type { RegisterDeviceRequest } from "./device";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * ═══════════════════════════════════════════════
 * DeviceService – device authentication & management
 * ═══════════════════════════════════════════════
 *
 * @generated from protobuf service auth.DeviceService
 */
export interface IDeviceServiceClient {
    /**
     * @generated from protobuf rpc: RegisterDevice
     */
    registerDevice(input: RegisterDeviceRequest, options?: RpcOptions): UnaryCall<RegisterDeviceRequest, RegisterDeviceResponse>;
    /**
     * @generated from protobuf rpc: ConfirmDevice
     */
    confirmDevice(input: ConfirmDeviceRequest, options?: RpcOptions): UnaryCall<ConfirmDeviceRequest, ConfirmDeviceResponse>;
    /**
     * @generated from protobuf rpc: GetUserDevices
     */
    getUserDevices(input: GetUserDevicesRequest, options?: RpcOptions): UnaryCall<GetUserDevicesRequest, GetUserDevicesResponse>;
    /**
     * @generated from protobuf rpc: GetDevice
     */
    getDevice(input: GetDeviceRequest, options?: RpcOptions): UnaryCall<GetDeviceRequest, Device>;
    /**
     * @generated from protobuf rpc: RevokeDevice
     */
    revokeDevice(input: RevokeDeviceRequest, options?: RpcOptions): UnaryCall<RevokeDeviceRequest, Empty>;
    /**
     * @generated from protobuf rpc: RevokeAllDevices
     */
    revokeAllDevices(input: RevokeAllDevicesRequest, options?: RpcOptions): UnaryCall<RevokeAllDevicesRequest, Empty>;
    /**
     * @generated from protobuf rpc: GetDeviceActivity
     */
    getDeviceActivity(input: GetDeviceActivityRequest, options?: RpcOptions): UnaryCall<GetDeviceActivityRequest, GetDeviceActivityResponse>;
    /**
     * @generated from protobuf rpc: UpdateDeviceActivity
     */
    updateDeviceActivity(input: UpdateDeviceActivityRequest, options?: RpcOptions): UnaryCall<UpdateDeviceActivityRequest, Empty>;
}
/**
 * ═══════════════════════════════════════════════
 * DeviceService – device authentication & management
 * ═══════════════════════════════════════════════
 *
 * @generated from protobuf service auth.DeviceService
 */
export class DeviceServiceClient implements IDeviceServiceClient, ServiceInfo {
    typeName = DeviceService.typeName;
    methods = DeviceService.methods;
    options = DeviceService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: RegisterDevice
     */
    registerDevice(input: RegisterDeviceRequest, options?: RpcOptions): UnaryCall<RegisterDeviceRequest, RegisterDeviceResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<RegisterDeviceRequest, RegisterDeviceResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ConfirmDevice
     */
    confirmDevice(input: ConfirmDeviceRequest, options?: RpcOptions): UnaryCall<ConfirmDeviceRequest, ConfirmDeviceResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<ConfirmDeviceRequest, ConfirmDeviceResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetUserDevices
     */
    getUserDevices(input: GetUserDevicesRequest, options?: RpcOptions): UnaryCall<GetUserDevicesRequest, GetUserDevicesResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetUserDevicesRequest, GetUserDevicesResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetDevice
     */
    getDevice(input: GetDeviceRequest, options?: RpcOptions): UnaryCall<GetDeviceRequest, Device> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetDeviceRequest, Device>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: RevokeDevice
     */
    revokeDevice(input: RevokeDeviceRequest, options?: RpcOptions): UnaryCall<RevokeDeviceRequest, Empty> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<RevokeDeviceRequest, Empty>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: RevokeAllDevices
     */
    revokeAllDevices(input: RevokeAllDevicesRequest, options?: RpcOptions): UnaryCall<RevokeAllDevicesRequest, Empty> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<RevokeAllDevicesRequest, Empty>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetDeviceActivity
     */
    getDeviceActivity(input: GetDeviceActivityRequest, options?: RpcOptions): UnaryCall<GetDeviceActivityRequest, GetDeviceActivityResponse> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetDeviceActivityRequest, GetDeviceActivityResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateDeviceActivity
     */
    updateDeviceActivity(input: UpdateDeviceActivityRequest, options?: RpcOptions): UnaryCall<UpdateDeviceActivityRequest, Empty> {
        const method = this.methods[7], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateDeviceActivityRequest, Empty>("unary", this._transport, method, opt, input);
    }
}
