/**
 * @fileoverview gRPC-Web generated client stub for payments
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v2.0.2
// 	protoc              v7.34.0
// source: subscription.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js')
const proto = {};
proto.payments = require('./subscription_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.payments.PaymentsServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.payments.PaymentsServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.payments.GetMySubscriptionRequest,
 *   !proto.payments.GetMySubscriptionResponse>}
 */
const methodDescriptor_PaymentsService_GetMySubscription = new grpc.web.MethodDescriptor(
  '/payments.PaymentsService/GetMySubscription',
  grpc.web.MethodType.UNARY,
  proto.payments.GetMySubscriptionRequest,
  proto.payments.GetMySubscriptionResponse,
  /**
   * @param {!proto.payments.GetMySubscriptionRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.payments.GetMySubscriptionResponse.deserializeBinary
);


/**
 * @param {!proto.payments.GetMySubscriptionRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.payments.GetMySubscriptionResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.payments.GetMySubscriptionResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.payments.PaymentsServiceClient.prototype.getMySubscription =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/payments.PaymentsService/GetMySubscription',
      request,
      metadata || {},
      methodDescriptor_PaymentsService_GetMySubscription,
      callback);
};


/**
 * @param {!proto.payments.GetMySubscriptionRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.payments.GetMySubscriptionResponse>}
 *     Promise that resolves to the response
 */
proto.payments.PaymentsServicePromiseClient.prototype.getMySubscription =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/payments.PaymentsService/GetMySubscription',
      request,
      metadata || {},
      methodDescriptor_PaymentsService_GetMySubscription);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.payments.CheckSubscriptionAccessRequest,
 *   !proto.payments.CheckSubscriptionAccessResponse>}
 */
const methodDescriptor_PaymentsService_CheckSubscriptionAccess = new grpc.web.MethodDescriptor(
  '/payments.PaymentsService/CheckSubscriptionAccess',
  grpc.web.MethodType.UNARY,
  proto.payments.CheckSubscriptionAccessRequest,
  proto.payments.CheckSubscriptionAccessResponse,
  /**
   * @param {!proto.payments.CheckSubscriptionAccessRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.payments.CheckSubscriptionAccessResponse.deserializeBinary
);


/**
 * @param {!proto.payments.CheckSubscriptionAccessRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.payments.CheckSubscriptionAccessResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.payments.CheckSubscriptionAccessResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.payments.PaymentsServiceClient.prototype.checkSubscriptionAccess =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/payments.PaymentsService/CheckSubscriptionAccess',
      request,
      metadata || {},
      methodDescriptor_PaymentsService_CheckSubscriptionAccess,
      callback);
};


/**
 * @param {!proto.payments.CheckSubscriptionAccessRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.payments.CheckSubscriptionAccessResponse>}
 *     Promise that resolves to the response
 */
proto.payments.PaymentsServicePromiseClient.prototype.checkSubscriptionAccess =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/payments.PaymentsService/CheckSubscriptionAccess',
      request,
      metadata || {},
      methodDescriptor_PaymentsService_CheckSubscriptionAccess);
};


module.exports = proto.payments;

