/**
 * @fileoverview gRPC-Web generated client stub for auth
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v2.0.2
// 	protoc              v7.34.0
// source: marketplace.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js')

var google_protobuf_struct_pb = require('google-protobuf/google/protobuf/struct_pb.js')
const proto = {};
proto.auth = require('./marketplace_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.auth.ShortlistServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.auth.ShortlistServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.auth.CreateShortlistReq,
 *   !proto.auth.JsonResponse>}
 */
const methodDescriptor_ShortlistService_CreateShortlist = new grpc.web.MethodDescriptor(
  '/auth.ShortlistService/CreateShortlist',
  grpc.web.MethodType.UNARY,
  proto.auth.CreateShortlistReq,
  proto.auth.JsonResponse,
  /**
   * @param {!proto.auth.CreateShortlistReq} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.auth.JsonResponse.deserializeBinary
);


/**
 * @param {!proto.auth.CreateShortlistReq} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.auth.JsonResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.auth.JsonResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.auth.ShortlistServiceClient.prototype.createShortlist =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/auth.ShortlistService/CreateShortlist',
      request,
      metadata || {},
      methodDescriptor_ShortlistService_CreateShortlist,
      callback);
};


/**
 * @param {!proto.auth.CreateShortlistReq} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.auth.JsonResponse>}
 *     Promise that resolves to the response
 */
proto.auth.ShortlistServicePromiseClient.prototype.createShortlist =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/auth.ShortlistService/CreateShortlist',
      request,
      metadata || {},
      methodDescriptor_ShortlistService_CreateShortlist);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.auth.IdRequest,
 *   !proto.google.protobuf.Empty>}
 */
const methodDescriptor_ShortlistService_DeleteShortlist = new grpc.web.MethodDescriptor(
  '/auth.ShortlistService/DeleteShortlist',
  grpc.web.MethodType.UNARY,
  proto.auth.IdRequest,
  google_protobuf_empty_pb.Empty,
  /**
   * @param {!proto.auth.IdRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  google_protobuf_empty_pb.Empty.deserializeBinary
);


/**
 * @param {!proto.auth.IdRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.protobuf.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.protobuf.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.auth.ShortlistServiceClient.prototype.deleteShortlist =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/auth.ShortlistService/DeleteShortlist',
      request,
      metadata || {},
      methodDescriptor_ShortlistService_DeleteShortlist,
      callback);
};


/**
 * @param {!proto.auth.IdRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.protobuf.Empty>}
 *     Promise that resolves to the response
 */
proto.auth.ShortlistServicePromiseClient.prototype.deleteShortlist =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/auth.ShortlistService/DeleteShortlist',
      request,
      metadata || {},
      methodDescriptor_ShortlistService_DeleteShortlist);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.auth.UserIdRequest,
 *   !proto.auth.JsonResponse>}
 */
const methodDescriptor_ShortlistService_ListByHousehold = new grpc.web.MethodDescriptor(
  '/auth.ShortlistService/ListByHousehold',
  grpc.web.MethodType.UNARY,
  proto.auth.UserIdRequest,
  proto.auth.JsonResponse,
  /**
   * @param {!proto.auth.UserIdRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.auth.JsonResponse.deserializeBinary
);


/**
 * @param {!proto.auth.UserIdRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.auth.JsonResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.auth.JsonResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.auth.ShortlistServiceClient.prototype.listByHousehold =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/auth.ShortlistService/ListByHousehold',
      request,
      metadata || {},
      methodDescriptor_ShortlistService_ListByHousehold,
      callback);
};


/**
 * @param {!proto.auth.UserIdRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.auth.JsonResponse>}
 *     Promise that resolves to the response
 */
proto.auth.ShortlistServicePromiseClient.prototype.listByHousehold =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/auth.ShortlistService/ListByHousehold',
      request,
      metadata || {},
      methodDescriptor_ShortlistService_ListByHousehold);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.auth.UserIdRequest,
 *   !proto.auth.CountResponse>}
 */
const methodDescriptor_ShortlistService_GetShortlistCount = new grpc.web.MethodDescriptor(
  '/auth.ShortlistService/GetShortlistCount',
  grpc.web.MethodType.UNARY,
  proto.auth.UserIdRequest,
  proto.auth.CountResponse,
  /**
   * @param {!proto.auth.UserIdRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.auth.CountResponse.deserializeBinary
);


/**
 * @param {!proto.auth.UserIdRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.auth.CountResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.auth.CountResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.auth.ShortlistServiceClient.prototype.getShortlistCount =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/auth.ShortlistService/GetShortlistCount',
      request,
      metadata || {},
      methodDescriptor_ShortlistService_GetShortlistCount,
      callback);
};


/**
 * @param {!proto.auth.UserIdRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.auth.CountResponse>}
 *     Promise that resolves to the response
 */
proto.auth.ShortlistServicePromiseClient.prototype.getShortlistCount =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/auth.ShortlistService/GetShortlistCount',
      request,
      metadata || {},
      methodDescriptor_ShortlistService_GetShortlistCount);
};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.auth.HireRequestServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.auth.HireRequestServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.auth.ListHireRequestsReq,
 *   !proto.auth.JsonResponse>}
 */
const methodDescriptor_HireRequestService_ListHireRequests = new grpc.web.MethodDescriptor(
  '/auth.HireRequestService/ListHireRequests',
  grpc.web.MethodType.UNARY,
  proto.auth.ListHireRequestsReq,
  proto.auth.JsonResponse,
  /**
   * @param {!proto.auth.ListHireRequestsReq} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.auth.JsonResponse.deserializeBinary
);


/**
 * @param {!proto.auth.ListHireRequestsReq} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.auth.JsonResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.auth.JsonResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.auth.HireRequestServiceClient.prototype.listHireRequests =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/auth.HireRequestService/ListHireRequests',
      request,
      metadata || {},
      methodDescriptor_HireRequestService_ListHireRequests,
      callback);
};


/**
 * @param {!proto.auth.ListHireRequestsReq} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.auth.JsonResponse>}
 *     Promise that resolves to the response
 */
proto.auth.HireRequestServicePromiseClient.prototype.listHireRequests =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/auth.HireRequestService/ListHireRequests',
      request,
      metadata || {},
      methodDescriptor_HireRequestService_ListHireRequests);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.auth.IdRequest,
 *   !proto.auth.JsonResponse>}
 */
const methodDescriptor_HireRequestService_AcceptHireRequest = new grpc.web.MethodDescriptor(
  '/auth.HireRequestService/AcceptHireRequest',
  grpc.web.MethodType.UNARY,
  proto.auth.IdRequest,
  proto.auth.JsonResponse,
  /**
   * @param {!proto.auth.IdRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.auth.JsonResponse.deserializeBinary
);


/**
 * @param {!proto.auth.IdRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.auth.JsonResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.auth.JsonResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.auth.HireRequestServiceClient.prototype.acceptHireRequest =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/auth.HireRequestService/AcceptHireRequest',
      request,
      metadata || {},
      methodDescriptor_HireRequestService_AcceptHireRequest,
      callback);
};


/**
 * @param {!proto.auth.IdRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.auth.JsonResponse>}
 *     Promise that resolves to the response
 */
proto.auth.HireRequestServicePromiseClient.prototype.acceptHireRequest =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/auth.HireRequestService/AcceptHireRequest',
      request,
      metadata || {},
      methodDescriptor_HireRequestService_AcceptHireRequest);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.auth.IdRequest,
 *   !proto.auth.JsonResponse>}
 */
const methodDescriptor_HireRequestService_DeclineHireRequest = new grpc.web.MethodDescriptor(
  '/auth.HireRequestService/DeclineHireRequest',
  grpc.web.MethodType.UNARY,
  proto.auth.IdRequest,
  proto.auth.JsonResponse,
  /**
   * @param {!proto.auth.IdRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.auth.JsonResponse.deserializeBinary
);


/**
 * @param {!proto.auth.IdRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.auth.JsonResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.auth.JsonResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.auth.HireRequestServiceClient.prototype.declineHireRequest =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/auth.HireRequestService/DeclineHireRequest',
      request,
      metadata || {},
      methodDescriptor_HireRequestService_DeclineHireRequest,
      callback);
};


/**
 * @param {!proto.auth.IdRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.auth.JsonResponse>}
 *     Promise that resolves to the response
 */
proto.auth.HireRequestServicePromiseClient.prototype.declineHireRequest =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/auth.HireRequestService/DeclineHireRequest',
      request,
      metadata || {},
      methodDescriptor_HireRequestService_DeclineHireRequest);
};


module.exports = proto.auth;

