// @generated by protobuf-ts 2.11.1 with parameter long_type_string
// @generated from protobuf file "events/events.proto" (package "events", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Timestamp } from "../google/protobuf/timestamp";
/**
 * @generated from protobuf message events.EventEnvelope
 */
export interface EventEnvelope {
    /**
     * @generated from protobuf field: string event_id = 1
     */
    eventId: string;
    /**
     * @generated from protobuf field: string event_type = 2
     */
    eventType: string;
    /**
     * @generated from protobuf field: int32 version = 3
     */
    version: number;
    /**
     * @generated from protobuf field: string source = 4
     */
    source: string;
    /**
     * @generated from protobuf field: string user_id = 5
     */
    userId: string;
    /**
     * @generated from protobuf field: string timestamp = 6
     */
    timestamp: string;
    /**
     * @generated from protobuf field: bytes data = 7
     */
    data: Uint8Array;
}
/**
 * Specific events for Auth service
 *
 * @generated from protobuf message events.OTPSent
 */
export interface OTPSent {
    /**
     * @generated from protobuf field: string user_id = 1
     */
    userId: string;
    /**
     * @generated from protobuf field: string target = 2
     */
    target: string;
    /**
     * @generated from protobuf field: string otp_code = 3
     */
    otpCode: string;
    /**
     * @generated from protobuf field: string verification_type = 4
     */
    verificationType: string;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp expires_at = 5
     */
    expiresAt?: Timestamp;
    /**
     * @generated from protobuf field: map<string, string> variables = 6
     */
    variables: {
        [key: string]: string;
    };
    /**
     * @generated from protobuf field: google.protobuf.Timestamp created_at = 7
     */
    createdAt?: Timestamp;
}
/**
 * @generated from protobuf message events.UserSignedUp
 */
export interface UserSignedUp {
    /**
     * @generated from protobuf field: string user_id = 1
     */
    userId: string;
    /**
     * @generated from protobuf field: string profile_type = 2
     */
    profileType: string;
    /**
     * @generated from protobuf field: string email = 3
     */
    email: string;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp created_at = 4
     */
    createdAt?: Timestamp;
}
/**
 * Specific events for Notifications service
 *
 * @generated from protobuf message events.NotificationCreated
 */
export interface NotificationCreated {
    /**
     * @generated from protobuf field: string user_id = 1
     */
    userId: string;
    /**
     * @generated from protobuf field: string title = 2
     */
    title: string;
    /**
     * @generated from protobuf field: string message = 3
     */
    message: string;
    /**
     * @generated from protobuf field: string type = 4
     */
    type: string;
    /**
     * @generated from protobuf field: map<string, string> metadata = 5
     */
    metadata: {
        [key: string]: string;
    };
    /**
     * @generated from protobuf field: google.protobuf.Timestamp created_at = 6
     */
    createdAt?: Timestamp;
}
/**
 * @generated from protobuf message events.BlastMessage
 */
export interface BlastMessage {
    /**
     * @generated from protobuf field: string title = 1
     */
    title: string;
    /**
     * @generated from protobuf field: string message = 2
     */
    message: string;
    /**
     * @generated from protobuf field: string filter_type = 3
     */
    filterType: string;
    /**
     * @generated from protobuf field: map<string, string> filter_params = 4
     */
    filterParams: {
        [key: string]: string;
    };
    /**
     * @generated from protobuf field: google.protobuf.Timestamp created_at = 5
     */
    createdAt?: Timestamp;
}
/**
 * Specific events for Payments service
 *
 * @generated from protobuf message events.PaymentCreated
 */
export interface PaymentCreated {
    /**
     * @generated from protobuf field: string payment_id = 1
     */
    paymentId: string;
    /**
     * @generated from protobuf field: string order_id = 2
     */
    orderId: string;
    /**
     * @generated from protobuf field: double amount = 3
     */
    amount: number;
    /**
     * @generated from protobuf field: string currency = 4
     */
    currency: string;
    /**
     * @generated from protobuf field: string user_id = 5
     */
    userId: string;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp created_at = 6
     */
    createdAt?: Timestamp;
}
/**
 * @generated from protobuf message events.PaymentSucceeded
 */
export interface PaymentSucceeded {
    /**
     * @generated from protobuf field: string payment_id = 1
     */
    paymentId: string;
    /**
     * @generated from protobuf field: string transaction_id = 2
     */
    transactionId: string;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp succeeded_at = 3
     */
    succeededAt?: Timestamp;
}
/**
 * @generated from protobuf message events.PaymentFailed
 */
export interface PaymentFailed {
    /**
     * @generated from protobuf field: string payment_id = 1
     */
    paymentId: string;
    /**
     * @generated from protobuf field: string reason = 2
     */
    reason: string;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp failed_at = 3
     */
    failedAt?: Timestamp;
}
/**
 * @generated from protobuf message events.SubscriptionCreated
 */
export interface SubscriptionCreated {
    /**
     * @generated from protobuf field: string subscription_id = 1
     */
    subscriptionId: string;
    /**
     * @generated from protobuf field: string user_id = 2
     */
    userId: string;
    /**
     * @generated from protobuf field: string plan_id = 3
     */
    planId: string;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp created_at = 4
     */
    createdAt?: Timestamp;
}
/**
 * @generated from protobuf message events.SubscriptionCancelled
 */
export interface SubscriptionCancelled {
    /**
     * @generated from protobuf field: string subscription_id = 1
     */
    subscriptionId: string;
    /**
     * @generated from protobuf field: string user_id = 2
     */
    userId: string;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp cancelled_at = 3
     */
    cancelledAt?: Timestamp;
}
/**
 * @generated from protobuf message events.OnboardingProgressUpdated
 */
export interface OnboardingProgressUpdated {
    /**
     * @generated from protobuf field: string user_id = 1
     */
    userId: string;
    /**
     * @generated from protobuf field: string step_name = 2
     */
    stepName: string;
    /**
     * @generated from protobuf field: string status = 3
     */
    status: string; // IN_PROGRESS, COMPLETED, FAILED
    /**
     * @generated from protobuf field: string message = 4
     */
    message: string;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp updated_at = 5
     */
    updatedAt?: Timestamp;
}
/**
 * @generated from protobuf message events.HouseholdUpdated
 */
export interface HouseholdUpdated {
    /**
     * @generated from protobuf field: string household_id = 1
     */
    householdId: string;
    /**
     * @generated from protobuf field: string user_id = 2
     */
    userId: string; // user who triggered the update
    /**
     * @generated from protobuf field: string action = 3
     */
    action: string; // MEMBER_JOINED, MEMBER_LEFT, PROFILE_UPDATED
    /**
     * @generated from protobuf field: string message = 4
     */
    message: string;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp updated_at = 5
     */
    updatedAt?: Timestamp;
}
/**
 * @generated from protobuf message events.SystemMaintenanceAlert
 */
export interface SystemMaintenanceAlert {
    /**
     * @generated from protobuf field: string alert_id = 1
     */
    alertId: string;
    /**
     * @generated from protobuf field: string message = 2
     */
    message: string;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp scheduled_at = 3
     */
    scheduledAt?: Timestamp;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp duration_minutes = 4
     */
    durationMinutes?: Timestamp; // Or use int32 duration_minutes
    /**
     * @generated from protobuf field: string severity = 5
     */
    severity: string; // INFO, WARNING, CRITICAL
}
// @generated message type with reflection information, may provide speed optimized methods
class EventEnvelope$Type extends MessageType<EventEnvelope> {
    constructor() {
        super("events.EventEnvelope", [
            { no: 1, name: "event_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "event_type", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "version", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "source", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "user_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "timestamp", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "data", kind: "scalar", T: 12 /*ScalarType.BYTES*/ }
        ]);
    }
    create(value?: PartialMessage<EventEnvelope>): EventEnvelope {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.eventId = "";
        message.eventType = "";
        message.version = 0;
        message.source = "";
        message.userId = "";
        message.timestamp = "";
        message.data = new Uint8Array(0);
        if (value !== undefined)
            reflectionMergePartial<EventEnvelope>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: EventEnvelope): EventEnvelope {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string event_id */ 1:
                    message.eventId = reader.string();
                    break;
                case /* string event_type */ 2:
                    message.eventType = reader.string();
                    break;
                case /* int32 version */ 3:
                    message.version = reader.int32();
                    break;
                case /* string source */ 4:
                    message.source = reader.string();
                    break;
                case /* string user_id */ 5:
                    message.userId = reader.string();
                    break;
                case /* string timestamp */ 6:
                    message.timestamp = reader.string();
                    break;
                case /* bytes data */ 7:
                    message.data = reader.bytes();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: EventEnvelope, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string event_id = 1; */
        if (message.eventId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.eventId);
        /* string event_type = 2; */
        if (message.eventType !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.eventType);
        /* int32 version = 3; */
        if (message.version !== 0)
            writer.tag(3, WireType.Varint).int32(message.version);
        /* string source = 4; */
        if (message.source !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.source);
        /* string user_id = 5; */
        if (message.userId !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.userId);
        /* string timestamp = 6; */
        if (message.timestamp !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.timestamp);
        /* bytes data = 7; */
        if (message.data.length)
            writer.tag(7, WireType.LengthDelimited).bytes(message.data);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message events.EventEnvelope
 */
export const EventEnvelope = new EventEnvelope$Type();
// @generated message type with reflection information, may provide speed optimized methods
class OTPSent$Type extends MessageType<OTPSent> {
    constructor() {
        super("events.OTPSent", [
            { no: 1, name: "user_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "target", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "otp_code", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "verification_type", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "expires_at", kind: "message", T: () => Timestamp },
            { no: 6, name: "variables", kind: "map", K: 9 /*ScalarType.STRING*/, V: { kind: "scalar", T: 9 /*ScalarType.STRING*/ } },
            { no: 7, name: "created_at", kind: "message", T: () => Timestamp }
        ]);
    }
    create(value?: PartialMessage<OTPSent>): OTPSent {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.userId = "";
        message.target = "";
        message.otpCode = "";
        message.verificationType = "";
        message.variables = {};
        if (value !== undefined)
            reflectionMergePartial<OTPSent>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: OTPSent): OTPSent {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string user_id */ 1:
                    message.userId = reader.string();
                    break;
                case /* string target */ 2:
                    message.target = reader.string();
                    break;
                case /* string otp_code */ 3:
                    message.otpCode = reader.string();
                    break;
                case /* string verification_type */ 4:
                    message.verificationType = reader.string();
                    break;
                case /* google.protobuf.Timestamp expires_at */ 5:
                    message.expiresAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.expiresAt);
                    break;
                case /* map<string, string> variables */ 6:
                    this.binaryReadMap6(message.variables, reader, options);
                    break;
                case /* google.protobuf.Timestamp created_at */ 7:
                    message.createdAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.createdAt);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    private binaryReadMap6(map: OTPSent["variables"], reader: IBinaryReader, options: BinaryReadOptions): void {
        let len = reader.uint32(), end = reader.pos + len, key: keyof OTPSent["variables"] | undefined, val: OTPSent["variables"][any] | undefined;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case 1:
                    key = reader.string();
                    break;
                case 2:
                    val = reader.string();
                    break;
                default: throw new globalThis.Error("unknown map entry field for events.OTPSent.variables");
            }
        }
        map[key ?? ""] = val ?? "";
    }
    internalBinaryWrite(message: OTPSent, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string user_id = 1; */
        if (message.userId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.userId);
        /* string target = 2; */
        if (message.target !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.target);
        /* string otp_code = 3; */
        if (message.otpCode !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.otpCode);
        /* string verification_type = 4; */
        if (message.verificationType !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.verificationType);
        /* google.protobuf.Timestamp expires_at = 5; */
        if (message.expiresAt)
            Timestamp.internalBinaryWrite(message.expiresAt, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        /* map<string, string> variables = 6; */
        for (let k of globalThis.Object.keys(message.variables))
            writer.tag(6, WireType.LengthDelimited).fork().tag(1, WireType.LengthDelimited).string(k).tag(2, WireType.LengthDelimited).string(message.variables[k]).join();
        /* google.protobuf.Timestamp created_at = 7; */
        if (message.createdAt)
            Timestamp.internalBinaryWrite(message.createdAt, writer.tag(7, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message events.OTPSent
 */
export const OTPSent = new OTPSent$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UserSignedUp$Type extends MessageType<UserSignedUp> {
    constructor() {
        super("events.UserSignedUp", [
            { no: 1, name: "user_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "profile_type", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "email", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "created_at", kind: "message", T: () => Timestamp }
        ]);
    }
    create(value?: PartialMessage<UserSignedUp>): UserSignedUp {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.userId = "";
        message.profileType = "";
        message.email = "";
        if (value !== undefined)
            reflectionMergePartial<UserSignedUp>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UserSignedUp): UserSignedUp {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string user_id */ 1:
                    message.userId = reader.string();
                    break;
                case /* string profile_type */ 2:
                    message.profileType = reader.string();
                    break;
                case /* string email */ 3:
                    message.email = reader.string();
                    break;
                case /* google.protobuf.Timestamp created_at */ 4:
                    message.createdAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.createdAt);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UserSignedUp, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string user_id = 1; */
        if (message.userId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.userId);
        /* string profile_type = 2; */
        if (message.profileType !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.profileType);
        /* string email = 3; */
        if (message.email !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.email);
        /* google.protobuf.Timestamp created_at = 4; */
        if (message.createdAt)
            Timestamp.internalBinaryWrite(message.createdAt, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message events.UserSignedUp
 */
export const UserSignedUp = new UserSignedUp$Type();
// @generated message type with reflection information, may provide speed optimized methods
class NotificationCreated$Type extends MessageType<NotificationCreated> {
    constructor() {
        super("events.NotificationCreated", [
            { no: 1, name: "user_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "title", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "type", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "metadata", kind: "map", K: 9 /*ScalarType.STRING*/, V: { kind: "scalar", T: 9 /*ScalarType.STRING*/ } },
            { no: 6, name: "created_at", kind: "message", T: () => Timestamp }
        ]);
    }
    create(value?: PartialMessage<NotificationCreated>): NotificationCreated {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.userId = "";
        message.title = "";
        message.message = "";
        message.type = "";
        message.metadata = {};
        if (value !== undefined)
            reflectionMergePartial<NotificationCreated>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: NotificationCreated): NotificationCreated {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string user_id */ 1:
                    message.userId = reader.string();
                    break;
                case /* string title */ 2:
                    message.title = reader.string();
                    break;
                case /* string message */ 3:
                    message.message = reader.string();
                    break;
                case /* string type */ 4:
                    message.type = reader.string();
                    break;
                case /* map<string, string> metadata */ 5:
                    this.binaryReadMap5(message.metadata, reader, options);
                    break;
                case /* google.protobuf.Timestamp created_at */ 6:
                    message.createdAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.createdAt);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    private binaryReadMap5(map: NotificationCreated["metadata"], reader: IBinaryReader, options: BinaryReadOptions): void {
        let len = reader.uint32(), end = reader.pos + len, key: keyof NotificationCreated["metadata"] | undefined, val: NotificationCreated["metadata"][any] | undefined;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case 1:
                    key = reader.string();
                    break;
                case 2:
                    val = reader.string();
                    break;
                default: throw new globalThis.Error("unknown map entry field for events.NotificationCreated.metadata");
            }
        }
        map[key ?? ""] = val ?? "";
    }
    internalBinaryWrite(message: NotificationCreated, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string user_id = 1; */
        if (message.userId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.userId);
        /* string title = 2; */
        if (message.title !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.title);
        /* string message = 3; */
        if (message.message !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.message);
        /* string type = 4; */
        if (message.type !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.type);
        /* map<string, string> metadata = 5; */
        for (let k of globalThis.Object.keys(message.metadata))
            writer.tag(5, WireType.LengthDelimited).fork().tag(1, WireType.LengthDelimited).string(k).tag(2, WireType.LengthDelimited).string(message.metadata[k]).join();
        /* google.protobuf.Timestamp created_at = 6; */
        if (message.createdAt)
            Timestamp.internalBinaryWrite(message.createdAt, writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message events.NotificationCreated
 */
export const NotificationCreated = new NotificationCreated$Type();
// @generated message type with reflection information, may provide speed optimized methods
class BlastMessage$Type extends MessageType<BlastMessage> {
    constructor() {
        super("events.BlastMessage", [
            { no: 1, name: "title", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "filter_type", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "filter_params", kind: "map", K: 9 /*ScalarType.STRING*/, V: { kind: "scalar", T: 9 /*ScalarType.STRING*/ } },
            { no: 5, name: "created_at", kind: "message", T: () => Timestamp }
        ]);
    }
    create(value?: PartialMessage<BlastMessage>): BlastMessage {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.title = "";
        message.message = "";
        message.filterType = "";
        message.filterParams = {};
        if (value !== undefined)
            reflectionMergePartial<BlastMessage>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: BlastMessage): BlastMessage {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string title */ 1:
                    message.title = reader.string();
                    break;
                case /* string message */ 2:
                    message.message = reader.string();
                    break;
                case /* string filter_type */ 3:
                    message.filterType = reader.string();
                    break;
                case /* map<string, string> filter_params */ 4:
                    this.binaryReadMap4(message.filterParams, reader, options);
                    break;
                case /* google.protobuf.Timestamp created_at */ 5:
                    message.createdAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.createdAt);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    private binaryReadMap4(map: BlastMessage["filterParams"], reader: IBinaryReader, options: BinaryReadOptions): void {
        let len = reader.uint32(), end = reader.pos + len, key: keyof BlastMessage["filterParams"] | undefined, val: BlastMessage["filterParams"][any] | undefined;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case 1:
                    key = reader.string();
                    break;
                case 2:
                    val = reader.string();
                    break;
                default: throw new globalThis.Error("unknown map entry field for events.BlastMessage.filter_params");
            }
        }
        map[key ?? ""] = val ?? "";
    }
    internalBinaryWrite(message: BlastMessage, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string title = 1; */
        if (message.title !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.title);
        /* string message = 2; */
        if (message.message !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.message);
        /* string filter_type = 3; */
        if (message.filterType !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.filterType);
        /* map<string, string> filter_params = 4; */
        for (let k of globalThis.Object.keys(message.filterParams))
            writer.tag(4, WireType.LengthDelimited).fork().tag(1, WireType.LengthDelimited).string(k).tag(2, WireType.LengthDelimited).string(message.filterParams[k]).join();
        /* google.protobuf.Timestamp created_at = 5; */
        if (message.createdAt)
            Timestamp.internalBinaryWrite(message.createdAt, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message events.BlastMessage
 */
export const BlastMessage = new BlastMessage$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PaymentCreated$Type extends MessageType<PaymentCreated> {
    constructor() {
        super("events.PaymentCreated", [
            { no: 1, name: "payment_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "order_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "amount", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 4, name: "currency", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "user_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "created_at", kind: "message", T: () => Timestamp }
        ]);
    }
    create(value?: PartialMessage<PaymentCreated>): PaymentCreated {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.paymentId = "";
        message.orderId = "";
        message.amount = 0;
        message.currency = "";
        message.userId = "";
        if (value !== undefined)
            reflectionMergePartial<PaymentCreated>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PaymentCreated): PaymentCreated {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string payment_id */ 1:
                    message.paymentId = reader.string();
                    break;
                case /* string order_id */ 2:
                    message.orderId = reader.string();
                    break;
                case /* double amount */ 3:
                    message.amount = reader.double();
                    break;
                case /* string currency */ 4:
                    message.currency = reader.string();
                    break;
                case /* string user_id */ 5:
                    message.userId = reader.string();
                    break;
                case /* google.protobuf.Timestamp created_at */ 6:
                    message.createdAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.createdAt);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PaymentCreated, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string payment_id = 1; */
        if (message.paymentId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.paymentId);
        /* string order_id = 2; */
        if (message.orderId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.orderId);
        /* double amount = 3; */
        if (message.amount !== 0)
            writer.tag(3, WireType.Bit64).double(message.amount);
        /* string currency = 4; */
        if (message.currency !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.currency);
        /* string user_id = 5; */
        if (message.userId !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.userId);
        /* google.protobuf.Timestamp created_at = 6; */
        if (message.createdAt)
            Timestamp.internalBinaryWrite(message.createdAt, writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message events.PaymentCreated
 */
export const PaymentCreated = new PaymentCreated$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PaymentSucceeded$Type extends MessageType<PaymentSucceeded> {
    constructor() {
        super("events.PaymentSucceeded", [
            { no: 1, name: "payment_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "transaction_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "succeeded_at", kind: "message", T: () => Timestamp }
        ]);
    }
    create(value?: PartialMessage<PaymentSucceeded>): PaymentSucceeded {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.paymentId = "";
        message.transactionId = "";
        if (value !== undefined)
            reflectionMergePartial<PaymentSucceeded>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PaymentSucceeded): PaymentSucceeded {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string payment_id */ 1:
                    message.paymentId = reader.string();
                    break;
                case /* string transaction_id */ 2:
                    message.transactionId = reader.string();
                    break;
                case /* google.protobuf.Timestamp succeeded_at */ 3:
                    message.succeededAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.succeededAt);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PaymentSucceeded, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string payment_id = 1; */
        if (message.paymentId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.paymentId);
        /* string transaction_id = 2; */
        if (message.transactionId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.transactionId);
        /* google.protobuf.Timestamp succeeded_at = 3; */
        if (message.succeededAt)
            Timestamp.internalBinaryWrite(message.succeededAt, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message events.PaymentSucceeded
 */
export const PaymentSucceeded = new PaymentSucceeded$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PaymentFailed$Type extends MessageType<PaymentFailed> {
    constructor() {
        super("events.PaymentFailed", [
            { no: 1, name: "payment_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "reason", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "failed_at", kind: "message", T: () => Timestamp }
        ]);
    }
    create(value?: PartialMessage<PaymentFailed>): PaymentFailed {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.paymentId = "";
        message.reason = "";
        if (value !== undefined)
            reflectionMergePartial<PaymentFailed>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PaymentFailed): PaymentFailed {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string payment_id */ 1:
                    message.paymentId = reader.string();
                    break;
                case /* string reason */ 2:
                    message.reason = reader.string();
                    break;
                case /* google.protobuf.Timestamp failed_at */ 3:
                    message.failedAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.failedAt);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PaymentFailed, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string payment_id = 1; */
        if (message.paymentId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.paymentId);
        /* string reason = 2; */
        if (message.reason !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.reason);
        /* google.protobuf.Timestamp failed_at = 3; */
        if (message.failedAt)
            Timestamp.internalBinaryWrite(message.failedAt, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message events.PaymentFailed
 */
export const PaymentFailed = new PaymentFailed$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SubscriptionCreated$Type extends MessageType<SubscriptionCreated> {
    constructor() {
        super("events.SubscriptionCreated", [
            { no: 1, name: "subscription_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "user_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "plan_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "created_at", kind: "message", T: () => Timestamp }
        ]);
    }
    create(value?: PartialMessage<SubscriptionCreated>): SubscriptionCreated {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.subscriptionId = "";
        message.userId = "";
        message.planId = "";
        if (value !== undefined)
            reflectionMergePartial<SubscriptionCreated>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SubscriptionCreated): SubscriptionCreated {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string subscription_id */ 1:
                    message.subscriptionId = reader.string();
                    break;
                case /* string user_id */ 2:
                    message.userId = reader.string();
                    break;
                case /* string plan_id */ 3:
                    message.planId = reader.string();
                    break;
                case /* google.protobuf.Timestamp created_at */ 4:
                    message.createdAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.createdAt);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SubscriptionCreated, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string subscription_id = 1; */
        if (message.subscriptionId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.subscriptionId);
        /* string user_id = 2; */
        if (message.userId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.userId);
        /* string plan_id = 3; */
        if (message.planId !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.planId);
        /* google.protobuf.Timestamp created_at = 4; */
        if (message.createdAt)
            Timestamp.internalBinaryWrite(message.createdAt, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message events.SubscriptionCreated
 */
export const SubscriptionCreated = new SubscriptionCreated$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SubscriptionCancelled$Type extends MessageType<SubscriptionCancelled> {
    constructor() {
        super("events.SubscriptionCancelled", [
            { no: 1, name: "subscription_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "user_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "cancelled_at", kind: "message", T: () => Timestamp }
        ]);
    }
    create(value?: PartialMessage<SubscriptionCancelled>): SubscriptionCancelled {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.subscriptionId = "";
        message.userId = "";
        if (value !== undefined)
            reflectionMergePartial<SubscriptionCancelled>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SubscriptionCancelled): SubscriptionCancelled {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string subscription_id */ 1:
                    message.subscriptionId = reader.string();
                    break;
                case /* string user_id */ 2:
                    message.userId = reader.string();
                    break;
                case /* google.protobuf.Timestamp cancelled_at */ 3:
                    message.cancelledAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.cancelledAt);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SubscriptionCancelled, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string subscription_id = 1; */
        if (message.subscriptionId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.subscriptionId);
        /* string user_id = 2; */
        if (message.userId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.userId);
        /* google.protobuf.Timestamp cancelled_at = 3; */
        if (message.cancelledAt)
            Timestamp.internalBinaryWrite(message.cancelledAt, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message events.SubscriptionCancelled
 */
export const SubscriptionCancelled = new SubscriptionCancelled$Type();
// @generated message type with reflection information, may provide speed optimized methods
class OnboardingProgressUpdated$Type extends MessageType<OnboardingProgressUpdated> {
    constructor() {
        super("events.OnboardingProgressUpdated", [
            { no: 1, name: "user_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "step_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "status", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "updated_at", kind: "message", T: () => Timestamp }
        ]);
    }
    create(value?: PartialMessage<OnboardingProgressUpdated>): OnboardingProgressUpdated {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.userId = "";
        message.stepName = "";
        message.status = "";
        message.message = "";
        if (value !== undefined)
            reflectionMergePartial<OnboardingProgressUpdated>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: OnboardingProgressUpdated): OnboardingProgressUpdated {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string user_id */ 1:
                    message.userId = reader.string();
                    break;
                case /* string step_name */ 2:
                    message.stepName = reader.string();
                    break;
                case /* string status */ 3:
                    message.status = reader.string();
                    break;
                case /* string message */ 4:
                    message.message = reader.string();
                    break;
                case /* google.protobuf.Timestamp updated_at */ 5:
                    message.updatedAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.updatedAt);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: OnboardingProgressUpdated, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string user_id = 1; */
        if (message.userId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.userId);
        /* string step_name = 2; */
        if (message.stepName !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.stepName);
        /* string status = 3; */
        if (message.status !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.status);
        /* string message = 4; */
        if (message.message !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.message);
        /* google.protobuf.Timestamp updated_at = 5; */
        if (message.updatedAt)
            Timestamp.internalBinaryWrite(message.updatedAt, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message events.OnboardingProgressUpdated
 */
export const OnboardingProgressUpdated = new OnboardingProgressUpdated$Type();
// @generated message type with reflection information, may provide speed optimized methods
class HouseholdUpdated$Type extends MessageType<HouseholdUpdated> {
    constructor() {
        super("events.HouseholdUpdated", [
            { no: 1, name: "household_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "user_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "action", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "updated_at", kind: "message", T: () => Timestamp }
        ]);
    }
    create(value?: PartialMessage<HouseholdUpdated>): HouseholdUpdated {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.householdId = "";
        message.userId = "";
        message.action = "";
        message.message = "";
        if (value !== undefined)
            reflectionMergePartial<HouseholdUpdated>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: HouseholdUpdated): HouseholdUpdated {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string household_id */ 1:
                    message.householdId = reader.string();
                    break;
                case /* string user_id */ 2:
                    message.userId = reader.string();
                    break;
                case /* string action */ 3:
                    message.action = reader.string();
                    break;
                case /* string message */ 4:
                    message.message = reader.string();
                    break;
                case /* google.protobuf.Timestamp updated_at */ 5:
                    message.updatedAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.updatedAt);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: HouseholdUpdated, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string household_id = 1; */
        if (message.householdId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.householdId);
        /* string user_id = 2; */
        if (message.userId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.userId);
        /* string action = 3; */
        if (message.action !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.action);
        /* string message = 4; */
        if (message.message !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.message);
        /* google.protobuf.Timestamp updated_at = 5; */
        if (message.updatedAt)
            Timestamp.internalBinaryWrite(message.updatedAt, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message events.HouseholdUpdated
 */
export const HouseholdUpdated = new HouseholdUpdated$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SystemMaintenanceAlert$Type extends MessageType<SystemMaintenanceAlert> {
    constructor() {
        super("events.SystemMaintenanceAlert", [
            { no: 1, name: "alert_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "scheduled_at", kind: "message", T: () => Timestamp },
            { no: 4, name: "duration_minutes", kind: "message", T: () => Timestamp },
            { no: 5, name: "severity", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<SystemMaintenanceAlert>): SystemMaintenanceAlert {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.alertId = "";
        message.message = "";
        message.severity = "";
        if (value !== undefined)
            reflectionMergePartial<SystemMaintenanceAlert>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SystemMaintenanceAlert): SystemMaintenanceAlert {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string alert_id */ 1:
                    message.alertId = reader.string();
                    break;
                case /* string message */ 2:
                    message.message = reader.string();
                    break;
                case /* google.protobuf.Timestamp scheduled_at */ 3:
                    message.scheduledAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.scheduledAt);
                    break;
                case /* google.protobuf.Timestamp duration_minutes */ 4:
                    message.durationMinutes = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.durationMinutes);
                    break;
                case /* string severity */ 5:
                    message.severity = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SystemMaintenanceAlert, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string alert_id = 1; */
        if (message.alertId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.alertId);
        /* string message = 2; */
        if (message.message !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.message);
        /* google.protobuf.Timestamp scheduled_at = 3; */
        if (message.scheduledAt)
            Timestamp.internalBinaryWrite(message.scheduledAt, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Timestamp duration_minutes = 4; */
        if (message.durationMinutes)
            Timestamp.internalBinaryWrite(message.durationMinutes, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* string severity = 5; */
        if (message.severity !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.severity);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message events.SystemMaintenanceAlert
 */
export const SystemMaintenanceAlert = new SystemMaintenanceAlert$Type();
