/**
 * @fileoverview gRPC-Web generated client stub for auth
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v2.0.2
// 	protoc              v7.34.0
// source: profile.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var google_protobuf_struct_pb = require('google-protobuf/google/protobuf/struct_pb.js')
const proto = {};
proto.auth = require('./profile_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.auth.ProfileServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.auth.ProfileServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.auth.UserIdRequest,
 *   !proto.auth.JsonResponse>}
 */
const methodDescriptor_ProfileService_GetCurrentHouseholdProfile = new grpc.web.MethodDescriptor(
  '/auth.ProfileService/GetCurrentHouseholdProfile',
  grpc.web.MethodType.UNARY,
  proto.auth.UserIdRequest,
  proto.auth.JsonResponse,
  /**
   * @param {!proto.auth.UserIdRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.auth.JsonResponse.deserializeBinary
);


/**
 * @param {!proto.auth.UserIdRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.auth.JsonResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.auth.JsonResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.auth.ProfileServiceClient.prototype.getCurrentHouseholdProfile =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/auth.ProfileService/GetCurrentHouseholdProfile',
      request,
      metadata || {},
      methodDescriptor_ProfileService_GetCurrentHouseholdProfile,
      callback);
};


/**
 * @param {!proto.auth.UserIdRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.auth.JsonResponse>}
 *     Promise that resolves to the response
 */
proto.auth.ProfileServicePromiseClient.prototype.getCurrentHouseholdProfile =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/auth.ProfileService/GetCurrentHouseholdProfile',
      request,
      metadata || {},
      methodDescriptor_ProfileService_GetCurrentHouseholdProfile);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.auth.UserIdRequest,
 *   !proto.auth.JsonResponse>}
 */
const methodDescriptor_ProfileService_GetHouseholdByUserID = new grpc.web.MethodDescriptor(
  '/auth.ProfileService/GetHouseholdByUserID',
  grpc.web.MethodType.UNARY,
  proto.auth.UserIdRequest,
  proto.auth.JsonResponse,
  /**
   * @param {!proto.auth.UserIdRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.auth.JsonResponse.deserializeBinary
);


/**
 * @param {!proto.auth.UserIdRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.auth.JsonResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.auth.JsonResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.auth.ProfileServiceClient.prototype.getHouseholdByUserID =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/auth.ProfileService/GetHouseholdByUserID',
      request,
      metadata || {},
      methodDescriptor_ProfileService_GetHouseholdByUserID,
      callback);
};


/**
 * @param {!proto.auth.UserIdRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.auth.JsonResponse>}
 *     Promise that resolves to the response
 */
proto.auth.ProfileServicePromiseClient.prototype.getHouseholdByUserID =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/auth.ProfileService/GetHouseholdByUserID',
      request,
      metadata || {},
      methodDescriptor_ProfileService_GetHouseholdByUserID);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.auth.SearchRequest,
 *   !proto.auth.JsonResponse>}
 */
const methodDescriptor_ProfileService_SearchHouseholds = new grpc.web.MethodDescriptor(
  '/auth.ProfileService/SearchHouseholds',
  grpc.web.MethodType.UNARY,
  proto.auth.SearchRequest,
  proto.auth.JsonResponse,
  /**
   * @param {!proto.auth.SearchRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.auth.JsonResponse.deserializeBinary
);


/**
 * @param {!proto.auth.SearchRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.auth.JsonResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.auth.JsonResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.auth.ProfileServiceClient.prototype.searchHouseholds =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/auth.ProfileService/SearchHouseholds',
      request,
      metadata || {},
      methodDescriptor_ProfileService_SearchHouseholds,
      callback);
};


/**
 * @param {!proto.auth.SearchRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.auth.JsonResponse>}
 *     Promise that resolves to the response
 */
proto.auth.ProfileServicePromiseClient.prototype.searchHouseholds =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/auth.ProfileService/SearchHouseholds',
      request,
      metadata || {},
      methodDescriptor_ProfileService_SearchHouseholds);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.auth.UserIdRequest,
 *   !proto.auth.JsonResponse>}
 */
const methodDescriptor_ProfileService_GetCurrentHousehelpProfile = new grpc.web.MethodDescriptor(
  '/auth.ProfileService/GetCurrentHousehelpProfile',
  grpc.web.MethodType.UNARY,
  proto.auth.UserIdRequest,
  proto.auth.JsonResponse,
  /**
   * @param {!proto.auth.UserIdRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.auth.JsonResponse.deserializeBinary
);


/**
 * @param {!proto.auth.UserIdRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.auth.JsonResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.auth.JsonResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.auth.ProfileServiceClient.prototype.getCurrentHousehelpProfile =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/auth.ProfileService/GetCurrentHousehelpProfile',
      request,
      metadata || {},
      methodDescriptor_ProfileService_GetCurrentHousehelpProfile,
      callback);
};


/**
 * @param {!proto.auth.UserIdRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.auth.JsonResponse>}
 *     Promise that resolves to the response
 */
proto.auth.ProfileServicePromiseClient.prototype.getCurrentHousehelpProfile =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/auth.ProfileService/GetCurrentHousehelpProfile',
      request,
      metadata || {},
      methodDescriptor_ProfileService_GetCurrentHousehelpProfile);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.auth.IdRequest,
 *   !proto.auth.JsonResponse>}
 */
const methodDescriptor_ProfileService_GetHousehelpByID = new grpc.web.MethodDescriptor(
  '/auth.ProfileService/GetHousehelpByID',
  grpc.web.MethodType.UNARY,
  proto.auth.IdRequest,
  proto.auth.JsonResponse,
  /**
   * @param {!proto.auth.IdRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.auth.JsonResponse.deserializeBinary
);


/**
 * @param {!proto.auth.IdRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.auth.JsonResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.auth.JsonResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.auth.ProfileServiceClient.prototype.getHousehelpByID =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/auth.ProfileService/GetHousehelpByID',
      request,
      metadata || {},
      methodDescriptor_ProfileService_GetHousehelpByID,
      callback);
};


/**
 * @param {!proto.auth.IdRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.auth.JsonResponse>}
 *     Promise that resolves to the response
 */
proto.auth.ProfileServicePromiseClient.prototype.getHousehelpByID =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/auth.ProfileService/GetHousehelpByID',
      request,
      metadata || {},
      methodDescriptor_ProfileService_GetHousehelpByID);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.auth.UserIdRequest,
 *   !proto.auth.JsonResponse>}
 */
const methodDescriptor_ProfileService_GetHousehelpByUserID = new grpc.web.MethodDescriptor(
  '/auth.ProfileService/GetHousehelpByUserID',
  grpc.web.MethodType.UNARY,
  proto.auth.UserIdRequest,
  proto.auth.JsonResponse,
  /**
   * @param {!proto.auth.UserIdRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.auth.JsonResponse.deserializeBinary
);


/**
 * @param {!proto.auth.UserIdRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.auth.JsonResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.auth.JsonResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.auth.ProfileServiceClient.prototype.getHousehelpByUserID =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/auth.ProfileService/GetHousehelpByUserID',
      request,
      metadata || {},
      methodDescriptor_ProfileService_GetHousehelpByUserID,
      callback);
};


/**
 * @param {!proto.auth.UserIdRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.auth.JsonResponse>}
 *     Promise that resolves to the response
 */
proto.auth.ProfileServicePromiseClient.prototype.getHousehelpByUserID =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/auth.ProfileService/GetHousehelpByUserID',
      request,
      metadata || {},
      methodDescriptor_ProfileService_GetHousehelpByUserID);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.auth.IdRequest,
 *   !proto.auth.JsonResponse>}
 */
const methodDescriptor_ProfileService_GetHousehelpProfileWithUser = new grpc.web.MethodDescriptor(
  '/auth.ProfileService/GetHousehelpProfileWithUser',
  grpc.web.MethodType.UNARY,
  proto.auth.IdRequest,
  proto.auth.JsonResponse,
  /**
   * @param {!proto.auth.IdRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.auth.JsonResponse.deserializeBinary
);


/**
 * @param {!proto.auth.IdRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.auth.JsonResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.auth.JsonResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.auth.ProfileServiceClient.prototype.getHousehelpProfileWithUser =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/auth.ProfileService/GetHousehelpProfileWithUser',
      request,
      metadata || {},
      methodDescriptor_ProfileService_GetHousehelpProfileWithUser,
      callback);
};


/**
 * @param {!proto.auth.IdRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.auth.JsonResponse>}
 *     Promise that resolves to the response
 */
proto.auth.ProfileServicePromiseClient.prototype.getHousehelpProfileWithUser =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/auth.ProfileService/GetHousehelpProfileWithUser',
      request,
      metadata || {},
      methodDescriptor_ProfileService_GetHousehelpProfileWithUser);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.auth.SearchRequest,
 *   !proto.auth.JsonResponse>}
 */
const methodDescriptor_ProfileService_SearchHousehelps = new grpc.web.MethodDescriptor(
  '/auth.ProfileService/SearchHousehelps',
  grpc.web.MethodType.UNARY,
  proto.auth.SearchRequest,
  proto.auth.JsonResponse,
  /**
   * @param {!proto.auth.SearchRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.auth.JsonResponse.deserializeBinary
);


/**
 * @param {!proto.auth.SearchRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.auth.JsonResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.auth.JsonResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.auth.ProfileServiceClient.prototype.searchHousehelps =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/auth.ProfileService/SearchHousehelps',
      request,
      metadata || {},
      methodDescriptor_ProfileService_SearchHousehelps,
      callback);
};


/**
 * @param {!proto.auth.SearchRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.auth.JsonResponse>}
 *     Promise that resolves to the response
 */
proto.auth.ProfileServicePromiseClient.prototype.searchHousehelps =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/auth.ProfileService/SearchHousehelps',
      request,
      metadata || {},
      methodDescriptor_ProfileService_SearchHousehelps);
};


module.exports = proto.auth;

